import Testing
@testable import Swiftiomatic

@Suite struct SingularizeTests {
    @Test func singularization() {
        #expect("aces".singularized() == "ace")
        #expect("addenda".singularized() == "addendum")
        #expect("aircraft".singularized() == "aircraft")
        #expect("aliases".singularized() == "alias")
        #expect("alumnae".singularized() == "alumna")
        #expect("alumni".singularized() == "alumnus")
        #expect("analyses".singularized() == "analysis")
        #expect("antennae".singularized() == "antenna")
        #expect("antennas".singularized() == "antenna")
        #expect("apexes".singularized() == "apex")
        #expect("apices".singularized() == "apex")
        #expect("appendices".singularized() == "appendix")
        #expect("axes".singularized() == "axis")
        #expect("bacilli".singularized() == "bacillus")
        #expect("backhoes".singularized() == "backhoe")
        #expect("bacteria".singularized() == "bacterium")
        #expect("bases".singularized() == "base")
        #expect("bison".singularized() == "bison")
        #expect("buses".singularized() == "bus")
        #expect("bureaux".singularized() == "bureau")
        #expect("cacti".singularized() == "cactus")
        #expect("cases".singularized() == "case")
        #expect("centers".singularized() == "center")
        #expect("children".singularized() == "child")
        #expect("cilia".singularized() == "cilium")
        #expect("codices".singularized() == "codex")
        #expect("curricula".singularized() == "curriculum")
        #expect("criteria".singularized() == "criterion")
        #expect("criteria".singularized() == "criterion")
        #expect("deer".singularized() == "deer")
        #expect("diagnoses".singularized() == "diagnosis")
        #expect("dice".singularized() == "die")
        #expect("dogs".singularized() == "dog")
        #expect("doormice".singularized() == "doormouse")
        #expect("dwarves".singularized() == "dwarf")
        #expect("ellipses".singularized() == "ellipsis")
        #expect("errata".singularized() == "erratum")
        #expect("fairies".singularized() == "fairy")
        #expect("faces".singularized() == "face")
        #expect("faxes".singularized() == "fax")
        #expect("fezes".singularized() == "fez")
        #expect("fezzes".singularized() == "fez")
        #expect("fish".singularized() == "fish")
        #expect("fishes".singularized() == "fish")
        #expect("foci".singularized() == "focus")
        #expect("foes".singularized() == "foe")
        #expect("formulae".singularized() == "formula")
        #expect("foxes".singularized() == "fox")
        #expect("fruit".singularized() == "fruit")
        #expect("fruits".singularized() == "fruit")
        #expect("fungi".singularized() == "fungus")
        #expect("funguses".singularized() == "fungus")
        #expect("geese".singularized() == "goose")
        #expect("genera".singularized() == "genus")
        #expect("graffiti".singularized() == "graffito")
        #expect("grandchildren".singularized() == "grandchild")
        #expect("grouse".singularized() == "grouse")
        #expect("grouses".singularized() == "grouse")
        #expect("halves".singularized() == "half")
        #expect("hooves".singularized() == "hoof")
        #expect("indices".singularized() == "index")
        #expect("items".singularized() == "item")
        #expect("knives".singularized() == "knife")
        #expect("larvae".singularized() == "larva")
        #expect("larvas".singularized() == "larva")
        #expect("leaves".singularized() == "leaf")
        #expect("libretti".singularized() == "libretto")
        #expect("librettos".singularized() == "libretto")
        #expect("lives".singularized() == "life")
        #expect("loaves".singularized() == "loaf")
        #expect("loci".singularized() == "locus")
        #expect("matrices".singularized() == "matrix")
        #expect("matrixes".singularized() == "matrix")
        #expect("memoranda".singularized() == "memorandum")
        #expect("mice".singularized() == "mouse")
        #expect("millennia".singularized() == "millennium")
        #expect("minutiae".singularized() == "minutia")
        #expect("moves".singularized() == "move")
        #expect("movies".singularized() == "movie")
        #expect("noobies".singularized() == "nooby")
        #expect("nebulae".singularized() == "nebula")
        #expect("nucleae".singularized() == "nucleus")
        #expect("oases".singularized() == "oasis")
        #expect("octopuses".singularized() == "octopus")
        #expect("octopi".singularized() == "octopus")
        #expect("offspring".singularized() == "offspring")
        #expect("opera".singularized() == "opus")
        #expect("opuses".singularized() == "opus")
        #expect("ova".singularized() == "ovum")
        #expect("oxen".singularized() == "ox")
        #expect("parentheses".singularized() == "parenthesis")
        #expect("people".singularized() == "person")
        #expect("phenomena".singularized() == "phenomenon")
        #expect("phenomenons".singularized() == "phenomenon")
        #expect("phyla".singularized() == "phylum")
        #expect("potatoes".singularized() == "potato")
        #expect("praxes".singularized() == "praxis")
        #expect("quizzes".singularized() == "quiz")
        #expect("radii".singularized() == "radius")
        #expect("referenda".singularized() == "referendum")
        #expect("referendums".singularized() == "referendum")
        #expect("salmon".singularized() == "salmon")
        #expect("scarfs".singularized() == "scarf")
        #expect("scarves".singularized() == "scarf")
        #expect("selves".singularized() == "self")
        #expect("series".singularized() == "series")
        #expect("sheep".singularized() == "sheep")
        #expect("shoes".singularized() == "shoe")
        #expect("shrimp".singularized() == "shrimp")
        #expect("shrimps".singularized() == "shrimp")
        #expect("sofas".singularized() == "sofa")
        #expect("species".singularized() == "species")
        #expect("statuses".singularized() == "status")
        #expect("stimuli".singularized() == "stimulus")
        #expect("strata".singularized() == "stratum")
        #expect("syllabi".singularized() == "syllabus")
        #expect("syllabuses".singularized() == "syllabus")
        #expect("symposia".singularized() == "symposium")
        #expect("symposiums".singularized() == "symposium")
        #expect("synopses".singularized() == "synopsis")
        #expect("swine".singularized() == "swine")
        #expect("tableaux".singularized() == "tableau")
        #expect("taxes".singularized() == "tax")
        #expect("teeth".singularized() == "tooth")
        #expect("theses".singularized() == "thesis")
        #expect("thieves".singularized() == "thief")
        #expect("toes".singularized() == "toe")
        #expect("tomatoes".singularized() == "tomato")
        #expect("trout".singularized() == "trout")
        #expect("trouts".singularized() == "trout")
        #expect("tuna".singularized() == "tuna")
        #expect("tunas".singularized() == "tuna")
        #expect("vertebrae".singularized() == "vertebra")
        #expect("vertebras".singularized() == "vertebra")
        #expect("vertices".singularized() == "vertex")
        #expect("villae".singularized() == "villa")
        #expect("viruses".singularized() == "virus")
        #expect("virii".singularized() == "virus")
        #expect("viri".singularized() == "virus")
        #expect("vitae".singularized() == "vita")
        #expect("vortexes".singularized() == "vortex")
        #expect("vortices".singularized() == "vortex")
        #expect("wharfs".singularized() == "wharf")
        #expect("wharves".singularized() == "wharf")
        #expect("wives".singularized() == "wife")
        #expect("wolves".singularized() == "wolf")
        #expect("women".singularized() == "woman")
        #expect("zombies".singularized() == "zombie")
    }

    @Test func preserveCase() {
        #expect("Axes".singularized() == "Axis")
        #expect("COMPUTERS".singularized() == "COMPUTER")
        #expect("Teeth".singularized() == "Tooth")
    }

    @Test func stripAllPrefix() {
        #expect("allWindows".singularized() == "window")
        #expect("AllTargets".singularized() == "Target")
    }

    @Test func dontUseDatumOrMedium() {
        #expect("data".singularized() == "data")
        #expect("media".singularized() == "media")
        #expect("allMedia".singularized() == "media")
    }

    @Test func dontSingularizeNonPlurals() {
        #expect("uppercase".singularized() == nil)
        #expect("uppercased".singularized() == nil)
        #expect("rotate".singularized() == nil)
        #expect("map".singularized() == nil)
        #expect("filter".singularized() == nil)
        #expect("capitalize".singularized() == nil)
        #expect("tessellate".singularized() == nil)
    }
}
