// swiftlint:disable:this file_length
// Generated by GeneratePipeline — do not edit

import SwiftiomaticSyntax

private let _registerAllRulesOnceImpl: Void = {
  RuleRegistry.shared.register(rules: allRules)
}()

extension RuleRegistry {
  /// Register all rules, should only be called once before any linting code is executed
  public static func registerAllRulesOnce() {
    _ = _registerAllRulesOnceImpl
  }
}

/// All available built-in rules
private let allRules: [any Rule.Type] = [
  AcronymsRule.self,
  AgentReviewRule.self,
  AndOperatorRule.self,
  AnyEliminationRule.self,
  AnyObjectProtocolRule.self,
  ApplicationMainRule.self,
  AssignmentWrappingRule.self,
  AsyncStreamSafetyRule.self,
  AsyncWithoutAwaitRule.self,
  AttributeNameSpacingRule.self,
  AttributePlacementRule.self,
  BalancedXCTestLifecycleRule.self,
  BlankLineAfterGuardRule.self,
  BlankLineAfterImportsRule.self,
  BlankLinesAroundMarkRule.self,
  BlankLinesBetweenImportsRule.self,
  BlankLinesBetweenScopesRule.self,
  BlanketDisableCommandRule.self,
  BlockBasedKVORule.self,
  BlockCommentsRule.self,
  CallParameterAlignmentRule.self,
  CaseIterableUsageRule.self,
  ClosingBraceRule.self,
  ClosureBodyLengthRule.self,
  ClosureEndIndentationRule.self,
  ClosureParameterPositionRule.self,
  ClosureSpacingRule.self,
  CodableEnumRawValueRule.self,
  CollectionAlignmentRule.self,
  CollectionTypeSelectionRule.self,
  ColonRule.self,
  CommaInheritanceRule.self,
  CommaRule.self,
  CommentSpacingRule.self,
  CompilerProtocolInitRule.self,
  ComputedAccessorsOrderRule.self,
  ConcurrencyModernizationRule.self,
  ConditionalAssignmentRule.self,
  ConditionalReturnsOnNewlineRule.self,
  ConsecutiveSpacesRule.self,
  ContainsOverFilterCountRule.self,
  ContainsOverFilterIsEmptyRule.self,
  ContainsOverFirstNotNilRule.self,
  ContainsOverRangeCheckRule.self,
  ContrastedOpeningBraceRule.self,
  ControlStatementParensRule.self,
  ConvenienceTypeRule.self,
  CyclomaticComplexityRule.self,
  DateForTimingRule.self,
  DeadSymbolsRule.self,
  DeclarationWhitespaceRule.self,
  DelegateToAsyncStreamRule.self,
  DeploymentTargetRule.self,
  DirectReturnRule.self,
  DiscardedNotificationCenterObserverRule.self,
  DiscouragedAssertRule.self,
  DiscouragedDirectInitRule.self,
  DiscouragedNoneNameRule.self,
  DiscouragedObjectLiteralRule.self,
  DiscouragedOptionalBooleanRule.self,
  DiscouragedOptionalCollectionRule.self,
  DocCommentsBeforeModifiersRule.self,
  DocCommentsRule.self,
  DontRepeatTypeInStaticPropertiesRule.self,
  DuplicateConditionsRule.self,
  DuplicateEnumCasesRule.self,
  DuplicateImportsRule.self,
  DuplicatedKeyInDictionaryLiteralRule.self,
  DynamicInlineRule.self,
  EmptyBracesRule.self,
  EmptyCollectionLiteralRule.self,
  EmptyCountRule.self,
  EmptyEnumArgumentsRule.self,
  EmptyExtensionsRule.self,
  EmptyParametersRule.self,
  EmptyStringRule.self,
  EmptyXCTestMethodRule.self,
  EnumCaseAssociatedValuesCountRule.self,
  EnumNamespacesRule.self,
  EnvironmentEntryRule.self,
  ExpiringTodoRule.self,
  ExplicitACLRule.self,
  ExplicitEnumRawValueRule.self,
  ExplicitInitRule.self,
  ExplicitSelfRule.self,
  ExplicitTopLevelACLRule.self,
  ExplicitTypeInterfaceRule.self,
  ExtensionAccessControlRule.self,
  ExtensionAccessModifierRule.self,
  FallthroughRule.self,
  FatalErrorMessageRule.self,
  FileHeaderRule.self,
  FileLengthRule.self,
  FileMacroRule.self,
  FileNameNoSpaceRule.self,
  FileNameRule.self,
  FileTypesOrderRule.self,
  FinalTestCaseRule.self,
  FireAndForgetTaskRule.self,
  FirstWhereRule.self,
  FlatMapOverMapReduceRule.self,
  ForWhereRule.self,
  ForceCastRule.self,
  ForceTryRule.self,
  ForceUnwrapRule.self,
  FoundationModernizationRule.self,
  FullyIndirectEnumRule.self,
  FunctionBodyLengthRule.self,
  FunctionDefaultParameterAtEndRule.self,
  FunctionNameSpacingRule.self,
  FunctionParameterCountRule.self,
  GenericConsolidationRule.self,
  GenericExtensionsRule.self,
  GenericTypeNameRule.self,
  HeaderFileNameRule.self,
  HoistAwaitRule.self,
  HoistTryRule.self,
  IdenticalOperandsRule.self,
  IdentifierNameRule.self,
  ImplicitOptionalInitializationRule.self,
  ImplicitReturnRule.self,
  ImplicitSelfCaptureRule.self,
  ImplicitlyUnwrappedOptionalRule.self,
  InclusiveLanguageRule.self,
  IncompatibleConcurrencyAnnotationRule.self,
  IndentationWidthRule.self,
  InlinableGenericRule.self,
  InvalidCommandRule.self,
  IsDisjointRule.self,
  JoinedDefaultParameterRule.self,
  LargeTupleRule.self,
  LastWhereRule.self,
  LazyChainRule.self,
  LeadingDelimitersRule.self,
  LeadingWhitespaceRule.self,
  LegacyCGGeometryFunctionsRule.self,
  LegacyConstantRule.self,
  LegacyConstructorRule.self,
  LegacyHashingRule.self,
  LegacyMultipleRule.self,
  LegacyNSGeometryFunctionsRule.self,
  LegacyObjcTypeRule.self,
  LegacyRandomRule.self,
  LineLengthRule.self,
  LinebreaksRule.self,
  LiteralExpressionEndIndentationRule.self,
  LocalDocCommentRule.self,
  LockAntiPatternsRule.self,
  LowerACLThanParentRule.self,
  MarkRule.self,
  MarkTypesRule.self,
  MinMaxOverSortedRule.self,
  MissingDocsRule.self,
  ModifierOrderRule.self,
  ModifiersOnSameLineRule.self,
  MultilineArgumentsBracketsRule.self,
  MultilineArgumentsRule.self,
  MultilineCallArgumentsRule.self,
  MultilineClosureAnonymousArgumentRule.self,
  MultilineFunctionChainsRule.self,
  MultilineLiteralBracketsRule.self,
  MultilineParametersBracketsRule.self,
  MultilineParametersRule.self,
  MultipleTrailingClosuresRule.self,
  MutationDuringIterationRule.self,
  NSLocalizedStringKeyRule.self,
  NSLocalizedStringRequireBundleRule.self,
  NSNumberInitAsFunctionReferenceRule.self,
  NSObjectPreferIsEqualRule.self,
  NamingHeuristicsRule.self,
  NestingRule.self,
  NoBlankLineInChainRule.self,
  NoEmptyBlockRule.self,
  NoExplicitOwnershipRule.self,
  NoExtensionAccessModifierRule.self,
  NoFallthroughOnlyRule.self,
  NoForceTryInTestsRule.self,
  NoForceUnwrapInTestsRule.self,
  NoGroupingExtensionRule.self,
  NoGuardInTestsRule.self,
  NoLabelsInCasePatternsRule.self,
  NoMagicNumbersRule.self,
  NoSpaceInMethodCallRule.self,
  NonOverridableClassDeclarationRule.self,
  NotificationCenterDetachmentRule.self,
  NumberSeparatorRule.self,
  ObjectLiteralRule.self,
  ObservationPitfallsRule.self,
  OneCasePerLineRule.self,
  OneDeclarationPerFileRule.self,
  OpeningBraceRule.self,
  OperatorUsageSpacingRule.self,
  OptionalDataStringConversionRule.self,
  OptionalEnumCaseMatchingRule.self,
  OrphanedDocCommentRule.self,
  OverriddenSuperCallRule.self,
  OverrideInExtensionRule.self,
  PatternMatchingKeywordsRule.self,
  PeriodSpacingRule.self,
  PreferAssetSymbolsRule.self,
  PreferCAttributeRule.self,
  PreferConditionListRule.self,
  PreferCountWhereRule.self,
  PreferFinalClassesRule.self,
  PreferForLoopRule.self,
  PreferKeyPathRule.self,
  PreferModuleSelectorRule.self,
  PreferSelfInStaticReferencesRule.self,
  PreferSourceLocationRule.self,
  PreferSpecializeAttributeRule.self,
  PreferSwiftTestingAssertionsRule.self,
  PreferSwiftTestingRule.self,
  PreferTypeCheckingRule.self,
  PreferWeakLetRule.self,
  PrefixedTopLevelConstantRule.self,
  PrivateOverFilePrivateRule.self,
  PrivateSubjectRule.self,
  PrivateSwiftUIStatePropertyRule.self,
  PrivateUnitTestRule.self,
  ProhibitedSuperRule.self,
  ProtocolPropertyAccessorsOrderRule.self,
  ReduceBooleanRule.self,
  ReduceIntoRule.self,
  RedundantBackticksRule.self,
  RedundantBreakInSwitchRule.self,
  RedundantClosureArgumentParensRule.self,
  RedundantClosureRule.self,
  RedundantDisableCommandRule.self,
  RedundantDiscardableLetRule.self,
  RedundantElseRule.self,
  RedundantEquatableRule.self,
  RedundantEscapingRule.self,
  RedundantExtensionACLRule.self,
  RedundantFileprivateRule.self,
  RedundantGetRule.self,
  RedundantInternalRule.self,
  RedundantMainActorViewRule.self,
  RedundantNilCoalescingRule.self,
  RedundantObjcAttributeRule.self,
  RedundantOverrideRule.self,
  RedundantParensRule.self,
  RedundantPropertyRule.self,
  RedundantPublicRule.self,
  RedundantSelfRule.self,
  RedundantSendableRule.self,
  RedundantSetAccessControlRule.self,
  RedundantStaticSelfRule.self,
  RedundantStringEnumValueRule.self,
  RedundantSynthesizedInitializerRule.self,
  RedundantThrowsRule.self,
  RedundantTypeAnnotationRule.self,
  RedundantViewBuilderRule.self,
  RedundantVoidReturnRule.self,
  RequiredDeinitRule.self,
  RequiredEnumCaseRule.self,
  ReturnArrowSpacingRule.self,
  ReturnValueFromVoidFunctionRule.self,
  SelfBindingRule.self,
  SelfInPropertyInitializationRule.self,
  SelfTypeOverTypeOfSelfRule.self,
  ShorthandArgumentRule.self,
  ShorthandOperatorRule.self,
  ShorthandOptionalBindingRule.self,
  SimplifyGenericConstraintsRule.self,
  SingleLineBodyRule.self,
  SinglePropertyPerLineRule.self,
  SingleTestClassRule.self,
  SortDeclarationsRule.self,
  SortEnumCasesRule.self,
  SortImportsRule.self,
  SortSwitchCasesRule.self,
  SortTypealiasesRule.self,
  SpaceAroundBracketsRule.self,
  SpaceAroundCommentsRule.self,
  SpaceAroundGenericsRule.self,
  SpaceAroundParensRule.self,
  SpaceInsideBracketsRule.self,
  SpaceInsideGenericsRule.self,
  SpaceInsideParensRule.self,
  StatementPositionRule.self,
  StaticOperatorRule.self,
  StaticOverFinalClassRule.self,
  StrictFilePrivateRule.self,
  StringDataConversionRule.self,
  StrongifiedSelfRule.self,
  StructuralDuplicationRule.self,
  SwiftModernizationRule.self,
  SwiftTestingTestCaseNamesRule.self,
  SwiftUILayoutRule.self,
  SwiftUISupersededPatternsRule.self,
  SwiftUIViewAntiPatternsRule.self,
  SwiftUIViewMemberOrderingRule.self,
  SwitchCaseAlignmentRule.self,
  SwitchCaseOnNewlineRule.self,
  SyntacticSugarRule.self,
  TestCaseAccessibilityRule.self,
  TodoRule.self,
  ToggleBoolRule.self,
  TrailingClosureEmptyParensRule.self,
  TrailingClosureRule.self,
  TrailingCommaRule.self,
  TrailingNewlineRule.self,
  TrailingSemicolonRule.self,
  TrailingWhitespaceRule.self,
  TypeBodyLengthRule.self,
  TypeContentsOrderRule.self,
  TypeNameRule.self,
  TypedThrowsRule.self,
  TypesafeArrayInitRule.self,
  URLMacroRule.self,
  UnavailableConditionRule.self,
  UnavailableFunctionRule.self,
  UnhandledThrowingTaskRule.self,
  UnownedVariableCaptureRule.self,
  UntypedErrorInCatchRule.self,
  UnusedClosureParameterRule.self,
  UnusedControlFlowLabelRule.self,
  UnusedDeclarationRule.self,
  UnusedEnumeratedRule.self,
  UnusedImportRule.self,
  UnusedOptionalBindingRule.self,
  UnusedParameterRule.self,
  UnusedSetterValueRule.self,
  UseEarlyExitsRule.self,
  ValidateDocumentationCommentsRule.self,
  ValidateTestCasesRule.self,
  VerticalParameterAlignmentRule.self,
  VerticalWhitespaceBetweenCasesRule.self,
  VerticalWhitespaceClosingBracesRule.self,
  VerticalWhitespaceOpeningBracesRule.self,
  VerticalWhitespaceRule.self,
  VoidFunctionInTernaryConditionRule.self,
  VoidReturnRule.self,
  XCTFailMessageRule.self,
  XCTSpecificMatcherRule.self,
  YodaConditionRule.self,
  ZeroOverExplicitInitRule.self,
]

// MARK: - Categories (derived from directory structure)

extension AcronymsRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension AgentReviewRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension AndOperatorRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension AnyEliminationRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension AnyObjectProtocolRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension ApplicationMainRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension AssignmentWrappingRule { static let category = RuleCategory(name: "multiline", subcategory: "wrapping") }
extension AsyncStreamSafetyRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension AsyncWithoutAwaitRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension AttributeNameSpacingRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension AttributePlacementRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension BalancedXCTestLifecycleRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension BlankLineAfterGuardRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension BlankLineAfterImportsRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension BlankLinesAroundMarkRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension BlankLinesBetweenImportsRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension BlankLinesBetweenScopesRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension BlanketDisableCommandRule { static let category = RuleCategory(name: "documentation", subcategory: "annotations") }
extension BlockBasedKVORule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension BlockCommentsRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension CallParameterAlignmentRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension CaseIterableUsageRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension ClosingBraceRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension ClosureBodyLengthRule { static let category = RuleCategory(name: "metrics", subcategory: "length") }
extension ClosureEndIndentationRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension ClosureParameterPositionRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension ClosureSpacingRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension CodableEnumRawValueRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension CollectionAlignmentRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension CollectionTypeSelectionRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension ColonRule { static let category = RuleCategory(name: "whitespace", subcategory: "punctuation") }
extension CommaInheritanceRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension CommaRule { static let category = RuleCategory(name: "whitespace", subcategory: "punctuation") }
extension CommentSpacingRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension CompilerProtocolInitRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension ComputedAccessorsOrderRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension ConcurrencyModernizationRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension ConditionalAssignmentRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension ConditionalReturnsOnNewlineRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension ConsecutiveSpacesRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension ContainsOverFilterCountRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension ContainsOverFilterIsEmptyRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension ContainsOverFirstNotNilRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension ContainsOverRangeCheckRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension ContrastedOpeningBraceRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension ControlStatementParensRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension ConvenienceTypeRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension CyclomaticComplexityRule { static let category = RuleCategory(name: "metrics", subcategory: "complexity") }
extension DateForTimingRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension DeadSymbolsRule { static let category = RuleCategory(name: "deadcode", subcategory: "duplication") }
extension DeclarationWhitespaceRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension DelegateToAsyncStreamRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension DeploymentTargetRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension DirectReturnRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension DiscardedNotificationCenterObserverRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension DiscouragedAssertRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension DiscouragedDirectInitRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension DiscouragedNoneNameRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension DiscouragedObjectLiteralRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension DiscouragedOptionalBooleanRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension DiscouragedOptionalCollectionRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension DocCommentsBeforeModifiersRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension DocCommentsRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension DontRepeatTypeInStaticPropertiesRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension DuplicateConditionsRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension DuplicateEnumCasesRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension DuplicateImportsRule { static let category = RuleCategory(name: "deadcode", subcategory: "duplication") }
extension DuplicatedKeyInDictionaryLiteralRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension DynamicInlineRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension EmptyBracesRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension EmptyCollectionLiteralRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension EmptyCountRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension EmptyEnumArgumentsRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension EmptyExtensionsRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension EmptyParametersRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension EmptyStringRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension EmptyXCTestMethodRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension EnumCaseAssociatedValuesCountRule { static let category = RuleCategory(name: "metrics", subcategory: "complexity") }
extension EnumNamespacesRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension EnvironmentEntryRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension ExpiringTodoRule { static let category = RuleCategory(name: "documentation", subcategory: "annotations") }
extension ExplicitACLRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension ExplicitEnumRawValueRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension ExplicitInitRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension ExplicitSelfRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension ExplicitTopLevelACLRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension ExplicitTypeInterfaceRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension ExtensionAccessControlRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension ExtensionAccessModifierRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension FallthroughRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension FatalErrorMessageRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension FileHeaderRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension FileLengthRule { static let category = RuleCategory(name: "metrics", subcategory: "length") }
extension FileMacroRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension FileNameNoSpaceRule { static let category = RuleCategory(name: "naming", subcategory: "files") }
extension FileNameRule { static let category = RuleCategory(name: "naming", subcategory: "files") }
extension FileTypesOrderRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension FinalTestCaseRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension FireAndForgetTaskRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension FirstWhereRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension FlatMapOverMapReduceRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension ForWhereRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension ForceCastRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension ForceTryRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension ForceUnwrapRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension FoundationModernizationRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension FullyIndirectEnumRule { static let category = RuleCategory(name: "redundancy", subcategory: "modifiers") }
extension FunctionBodyLengthRule { static let category = RuleCategory(name: "metrics", subcategory: "length") }
extension FunctionDefaultParameterAtEndRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension FunctionNameSpacingRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension FunctionParameterCountRule { static let category = RuleCategory(name: "metrics", subcategory: "complexity") }
extension GenericConsolidationRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension GenericExtensionsRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension GenericTypeNameRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension HeaderFileNameRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension HoistAwaitRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension HoistTryRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension IdenticalOperandsRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension IdentifierNameRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension ImplicitOptionalInitializationRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension ImplicitReturnRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension ImplicitSelfCaptureRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension ImplicitlyUnwrappedOptionalRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension InclusiveLanguageRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension IncompatibleConcurrencyAnnotationRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension IndentationWidthRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension InlinableGenericRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension InvalidCommandRule { static let category = RuleCategory(name: "documentation", subcategory: "annotations") }
extension IsDisjointRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension JoinedDefaultParameterRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension LargeTupleRule { static let category = RuleCategory(name: "metrics", subcategory: "complexity") }
extension LastWhereRule { static let category = RuleCategory(name: "performance", subcategory: "collections") }
extension LazyChainRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension LeadingDelimitersRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension LeadingWhitespaceRule { static let category = RuleCategory(name: "whitespace", subcategory: "lineendings") }
extension LegacyCGGeometryFunctionsRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyConstantRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyConstructorRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyHashingRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyMultipleRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyNSGeometryFunctionsRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyObjcTypeRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LegacyRandomRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension LineLengthRule { static let category = RuleCategory(name: "metrics", subcategory: "length") }
extension LinebreaksRule { static let category = RuleCategory(name: "whitespace", subcategory: "lineendings") }
extension LiteralExpressionEndIndentationRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension LocalDocCommentRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension LockAntiPatternsRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension LowerACLThanParentRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension MarkRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension MarkTypesRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension MinMaxOverSortedRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension MissingDocsRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension ModifierOrderRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "modifiers") }
extension ModifiersOnSameLineRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "modifiers") }
extension MultilineArgumentsBracketsRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultilineArgumentsRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultilineCallArgumentsRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultilineClosureAnonymousArgumentRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension MultilineFunctionChainsRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultilineLiteralBracketsRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultilineParametersBracketsRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultilineParametersRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MultipleTrailingClosuresRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension MutationDuringIterationRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension NSLocalizedStringKeyRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension NSLocalizedStringRequireBundleRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension NSNumberInitAsFunctionReferenceRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension NSObjectPreferIsEqualRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension NamingHeuristicsRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension NestingRule { static let category = RuleCategory(name: "metrics", subcategory: "complexity") }
extension NoBlankLineInChainRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension NoEmptyBlockRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension NoExplicitOwnershipRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "modifiers") }
extension NoExtensionAccessModifierRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension NoFallthroughOnlyRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension NoForceTryInTestsRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension NoForceUnwrapInTestsRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension NoGroupingExtensionRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension NoGuardInTestsRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension NoLabelsInCasePatternsRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension NoMagicNumbersRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension NoSpaceInMethodCallRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension NonOverridableClassDeclarationRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "modifiers") }
extension NotificationCenterDetachmentRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension NumberSeparatorRule { static let category = RuleCategory(name: "multiline", subcategory: "arguments") }
extension ObjectLiteralRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension ObservationPitfallsRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension OneCasePerLineRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension OneDeclarationPerFileRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension OpeningBraceRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension OperatorUsageSpacingRule { static let category = RuleCategory(name: "whitespace", subcategory: "punctuation") }
extension OptionalDataStringConversionRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension OptionalEnumCaseMatchingRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension OrphanedDocCommentRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension OverriddenSuperCallRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension OverrideInExtensionRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension PatternMatchingKeywordsRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension PeriodSpacingRule { static let category = RuleCategory(name: "whitespace", subcategory: "punctuation") }
extension PreferAssetSymbolsRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension PreferCAttributeRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension PreferConditionListRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension PreferCountWhereRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension PreferFinalClassesRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension PreferForLoopRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension PreferKeyPathRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension PreferModuleSelectorRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension PreferSelfInStaticReferencesRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension PreferSourceLocationRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension PreferSpecializeAttributeRule { static let category = RuleCategory(name: "modernization", subcategory: "legacy") }
extension PreferSwiftTestingAssertionsRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension PreferSwiftTestingRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension PreferTypeCheckingRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension PreferWeakLetRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension PrefixedTopLevelConstantRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension PrivateOverFilePrivateRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension PrivateSubjectRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension PrivateSwiftUIStatePropertyRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension PrivateUnitTestRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension ProhibitedSuperRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension ProtocolPropertyAccessorsOrderRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension ReduceBooleanRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension ReduceIntoRule { static let category = RuleCategory(name: "performance", subcategory: "algorithms") }
extension RedundantBackticksRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantBreakInSwitchRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantClosureArgumentParensRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension RedundantClosureRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantDisableCommandRule { static let category = RuleCategory(name: "documentation", subcategory: "annotations") }
extension RedundantDiscardableLetRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension RedundantElseRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension RedundantEquatableRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension RedundantEscapingRule { static let category = RuleCategory(name: "redundancy", subcategory: "modifiers") }
extension RedundantExtensionACLRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantFileprivateRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantGetRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension RedundantInternalRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantMainActorViewRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension RedundantNilCoalescingRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension RedundantObjcAttributeRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantOverrideRule { static let category = RuleCategory(name: "redundancy", subcategory: "modifiers") }
extension RedundantParensRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantPropertyRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantPublicRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantSelfRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantSendableRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantSetAccessControlRule { static let category = RuleCategory(name: "redundancy", subcategory: "visibility") }
extension RedundantStaticSelfRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantStringEnumValueRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension RedundantSynthesizedInitializerRule { static let category = RuleCategory(name: "redundancy", subcategory: "modifiers") }
extension RedundantThrowsRule { static let category = RuleCategory(name: "redundancy", subcategory: "modifiers") }
extension RedundantTypeAnnotationRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension RedundantViewBuilderRule { static let category = RuleCategory(name: "redundancy", subcategory: "syntax") }
extension RedundantVoidReturnRule { static let category = RuleCategory(name: "redundancy", subcategory: "modifiers") }
extension RequiredDeinitRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension RequiredEnumCaseRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension ReturnArrowSpacingRule { static let category = RuleCategory(name: "whitespace", subcategory: "punctuation") }
extension ReturnValueFromVoidFunctionRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension SelfBindingRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension SelfInPropertyInitializationRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension SelfTypeOverTypeOfSelfRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension ShorthandArgumentRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension ShorthandOperatorRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension ShorthandOptionalBindingRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension SimplifyGenericConstraintsRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
extension SingleLineBodyRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension SinglePropertyPerLineRule { static let category = RuleCategory(name: "multiline", subcategory: "wrapping") }
extension SingleTestClassRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension SortDeclarationsRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension SortEnumCasesRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension SortImportsRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension SortSwitchCasesRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension SortTypealiasesRule { static let category = RuleCategory(name: "ordering", subcategory: "sorting") }
extension SpaceAroundBracketsRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension SpaceAroundCommentsRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension SpaceAroundGenericsRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension SpaceAroundParensRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension SpaceInsideBracketsRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension SpaceInsideGenericsRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension SpaceInsideParensRule { static let category = RuleCategory(name: "whitespace", subcategory: "horizontalspacing") }
extension StatementPositionRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension StaticOperatorRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "modifiers") }
extension StaticOverFinalClassRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "modifiers") }
extension StrictFilePrivateRule { static let category = RuleCategory(name: "accesscontrol", subcategory: "scope") }
extension StringDataConversionRule { static let category = RuleCategory(name: "typesafety", subcategory: "optionals") }
extension StrongifiedSelfRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension StructuralDuplicationRule { static let category = RuleCategory(name: "deadcode", subcategory: "duplication") }
extension SwiftModernizationRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension SwiftTestingTestCaseNamesRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension SwiftUILayoutRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension SwiftUISupersededPatternsRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension SwiftUIViewAntiPatternsRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension SwiftUIViewMemberOrderingRule { static let category = RuleCategory(name: "frameworks", subcategory: "swiftui") }
extension SwitchCaseAlignmentRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension SwitchCaseOnNewlineRule { static let category = RuleCategory(name: "whitespace", subcategory: "braces") }
extension SyntacticSugarRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension TestCaseAccessibilityRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension TodoRule { static let category = RuleCategory(name: "documentation", subcategory: "annotations") }
extension ToggleBoolRule { static let category = RuleCategory(name: "redundancy", subcategory: "expressions") }
extension TrailingClosureEmptyParensRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension TrailingClosureRule { static let category = RuleCategory(name: "controlflow", subcategory: "closures") }
extension TrailingCommaRule { static let category = RuleCategory(name: "whitespace", subcategory: "lineendings") }
extension TrailingNewlineRule { static let category = RuleCategory(name: "whitespace", subcategory: "lineendings") }
extension TrailingSemicolonRule { static let category = RuleCategory(name: "whitespace", subcategory: "punctuation") }
extension TrailingWhitespaceRule { static let category = RuleCategory(name: "whitespace", subcategory: "lineendings") }
extension TypeBodyLengthRule { static let category = RuleCategory(name: "metrics", subcategory: "length") }
extension TypeContentsOrderRule { static let category = RuleCategory(name: "ordering", subcategory: "structure") }
extension TypeNameRule { static let category = RuleCategory(name: "naming", subcategory: "identifiers") }
extension TypedThrowsRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension TypesafeArrayInitRule { static let category = RuleCategory(name: "typesafety", subcategory: "types") }
extension URLMacroRule { static let category = RuleCategory(name: "frameworks", subcategory: "foundation") }
extension UnavailableConditionRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension UnavailableFunctionRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension UnhandledThrowingTaskRule { static let category = RuleCategory(name: "modernization", subcategory: "concurrency") }
extension UnownedVariableCaptureRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UntypedErrorInCatchRule { static let category = RuleCategory(name: "typesafety", subcategory: "correctness") }
extension UnusedClosureParameterRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UnusedControlFlowLabelRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UnusedDeclarationRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UnusedEnumeratedRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UnusedImportRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UnusedOptionalBindingRule { static let category = RuleCategory(name: "controlflow", subcategory: "patterns") }
extension UnusedParameterRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UnusedSetterValueRule { static let category = RuleCategory(name: "deadcode", subcategory: "unused") }
extension UseEarlyExitsRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension ValidateDocumentationCommentsRule { static let category = RuleCategory(name: "documentation", subcategory: "comments") }
extension ValidateTestCasesRule { static let category = RuleCategory(name: "testing", subcategory: "practices") }
extension VerticalParameterAlignmentRule { static let category = RuleCategory(name: "multiline", subcategory: "alignment") }
extension VerticalWhitespaceBetweenCasesRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension VerticalWhitespaceClosingBracesRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension VerticalWhitespaceOpeningBracesRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension VerticalWhitespaceRule { static let category = RuleCategory(name: "whitespace", subcategory: "verticalspacing") }
extension VoidFunctionInTernaryConditionRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension VoidReturnRule { static let category = RuleCategory(name: "controlflow", subcategory: "returns") }
extension XCTFailMessageRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension XCTSpecificMatcherRule { static let category = RuleCategory(name: "testing", subcategory: "assertions") }
extension YodaConditionRule { static let category = RuleCategory(name: "controlflow", subcategory: "conditionals") }
extension ZeroOverExplicitInitRule { static let category = RuleCategory(name: "redundancy", subcategory: "types") }
