import SwiftSyntax

// Sandbox demonstrations of each pass-classification bucket.
//
// These rules are intentionally outside `Sources/SwiftiomaticKit/Rules/` so the
// `Generator`'s `RuleCollector` does not auto-register them — they exist only to
// document the intended shape of a rule in each locality × write-surface bucket and
// to verify the marker protocols compose correctly with `RewriteSyntaxRule`.
//
// Do not promote these into `Rules/` without:
//   1. real lint messages and configuration,
//   2. a sibling test file under `Tests/SwiftiomaticTests/Rules/`, and
//   3. a registration entry generated by `RuleCollector` (automatic once moved).

/// Token-local + token-text rewrite. Capitalizes any identifier whose text starts with
/// `__example_` — purely token-local because the decision uses only the token itself.
final class ExampleTokenLocalRule: RewriteSyntaxRule<BasicRuleValue>, @unchecked Sendable,
    TokenLocalFormatRule, TokenTextFormatRule, IdempotentFormatRule
{
    override func visit(_ token: TokenSyntax) -> TokenSyntax {
        guard case .identifier(let text) = token.tokenKind, text.hasPrefix("__example_") else {
            return token
        }
        return token.with(\.tokenKind, .identifier(text.uppercased()))
    }
}

/// Node-local + expression rewrite. Replaces `[Element]()` with `[]` when the element
/// type is inferable — node-local because the decision uses only the call expression.
final class ExampleNodeLocalRule: RewriteSyntaxRule<BasicRuleValue>, @unchecked Sendable,
    NodeLocalFormatRule, ExpressionRewriteFormatRule, IdempotentFormatRule
{
    override func visit(_ node: FunctionCallExprSyntax) -> ExprSyntax {
        guard node.arguments.isEmpty,
            let array = node.calledExpression.as(ArrayExprSyntax.self),
            array.elements.count == 1
        else { return ExprSyntax(node) }
        return ExprSyntax(
            ArrayExprSyntax(
                leftSquare: .leftSquareToken(),
                elements: ArrayElementListSyntax([]),
                rightSquare: .rightSquareToken()
            )
        )
    }
}

/// Decl-local + decl rewrite. Strips a redundant `internal` modifier from a function
/// declaration. Decl-local because the decision uses the visited decl's modifier list.
final class ExampleDeclLocalRule: RewriteSyntaxRule<BasicRuleValue>, @unchecked Sendable,
    DeclLocalFormatRule, DeclRewriteFormatRule
{
    override func visit(_ node: FunctionDeclSyntax) -> DeclSyntax {
        let stripped = node.modifiers.filter { $0.name.tokenKind != .keyword(.internal) }
        guard stripped.count != node.modifiers.count else { return DeclSyntax(node) }
        return DeclSyntax(node.with(\.modifiers, DeclModifierListSyntax(stripped)))
    }
}

/// Block-local + trivia-only on `.blankLines`. Demonstrates a rule that needs sibling
/// context (the surrounding member list) but writes only blank-line trivia.
final class ExampleBlockLocalRule: RewriteSyntaxRule<BasicRuleValue>, @unchecked Sendable,
    BlockLocalFormatRule, TriviaOnlyFormatRule, MonotonicWriteFormatRule
{
    static var channel: TriviaChannel { .blankLines }
    static var monotonicChannel: TriviaChannel { .blankLines }
    static var monotonicDirection: MonotonicDirection { .add }

    override func visit(_ node: MemberBlockItemListSyntax) -> MemberBlockItemListSyntax {
        var items = Array(node)
        guard items.count > 1 else { return node }
        for index in 1..<items.count {
            var item = items[index]
            if !item.leadingTrivia.contains(where: { $0.isNewline }) {
                item.leadingTrivia = .newline + item.leadingTrivia
            }
            items[index] = item
        }
        return MemberBlockItemListSyntax(items)
    }
}

/// File-global + list-reshaping on the top-level import list. The catch-all bucket —
/// runs as a solo pass. Demonstrates `ListReshapingFormatRule`'s `CollectionKind` slot.
final class ExampleFileGlobalRule: RewriteSyntaxRule<BasicRuleValue>, @unchecked Sendable,
    FileGlobalFormatRule, ListReshapingFormatRule
{
    typealias CollectionKind = CodeBlockItemListSyntax

    override func visit(_ node: SourceFileSyntax) -> SourceFileSyntax {
        let items = Array(node.statements)
        let imports = items.filter { $0.item.is(ImportDeclSyntax.self) }
        let rest = items.filter { !$0.item.is(ImportDeclSyntax.self) }
        let sorted = imports.sorted { lhs, rhs in
            lhs.item.description < rhs.item.description
        }
        return node.with(\.statements, CodeBlockItemListSyntax(sorted + rest))
    }
}
