//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

// This file is automatically generated with generate-swiftiomatic. Do not edit!

import SwiftSyntax

/// A syntax visitor that delegates to individual rules for linting.
///
/// This file will be extended with `visit` methods in Pipelines+Generated.swift.
class LintPipeline: SyntaxVisitor {

  /// The formatter context.
  let context: Context

  /// Stores lint and format rule instances, indexed by the `ObjectIdentifier` of a rule's
  /// class type.
  var ruleCache = [ObjectIdentifier: Rule]()

  /// Rules present in this dictionary skip visiting children until they leave the
  /// syntax node stored as their value
  var shouldSkipChildren = [ObjectIdentifier: SyntaxProtocol]()

  /// Creates a new lint pipeline.
  init(context: Context) {
    self.context = context
    super.init(viewMode: .sourceAccurate)
  }

  override func visit(_ node: AccessorBlockSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoEmptyLinesOpeningClosingBraces.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AccessorBlockSyntax) {
    onVisitPost(rule: NoEmptyLinesOpeningClosingBraces.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
  }

  override func visit(_ node: AccessorDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(RedundantSelf.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AccessorDeclSyntax) {
    onVisitPost(rule: RedundantSelf.self, for: node)
  }

  override func visit(_ node: ActorDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantSwiftTestingSuite.visit, for: node)
    visitIfEnabled(SimplifyGenericConstraints.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ActorDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantSwiftTestingSuite.self, for: node)
    onVisitPost(rule: SimplifyGenericConstraints.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: AsExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AsExprSyntax) {
    onVisitPost(rule: NoForceUnwrap.self, for: node)
  }

  override func visit(_ node: AssociatedTypeDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AssociatedTypeDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: AttributeSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoRetroactiveConformances.visit, for: node)
    visitIfEnabled(PreferMainAttribute.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AttributeSyntax) {
    onVisitPost(rule: NoRetroactiveConformances.self, for: node)
    onVisitPost(rule: PreferMainAttribute.self, for: node)
  }

  override func visit(_ node: AttributedTypeSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoExplicitOwnership.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AttributedTypeSyntax) {
    onVisitPost(rule: NoExplicitOwnership.self, for: node)
  }

  override func visit(_ node: AwaitExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(HoistTry.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: AwaitExprSyntax) {
    onVisitPost(rule: HoistTry.self, for: node)
  }

  override func visit(_ node: CatchClauseSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(RedundantLetError.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: CatchClauseSyntax) {
    onVisitPost(rule: RedundantLetError.self, for: node)
  }

  override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(EnumNamespaces.visit, for: node)
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoForceTry.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(NoGuardInTests.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    visitIfEnabled(PreferFinalClasses.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantSwiftTestingSuite.visit, for: node)
    visitIfEnabled(SimplifyGenericConstraints.visit, for: node)
    visitIfEnabled(TestSuiteAccessControl.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(ValidateTestCases.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ClassDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: EnumNamespaces.self, for: node)
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoForceTry.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: NoGuardInTests.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
    onVisitPost(rule: PreferFinalClasses.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantSwiftTestingSuite.self, for: node)
    onVisitPost(rule: SimplifyGenericConstraints.self, for: node)
    onVisitPost(rule: TestSuiteAccessControl.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: ValidateTestCases.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: ClosureExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(EmptyBraces.visit, for: node)
    visitIfEnabled(NoEmptyLinesOpeningClosingBraces.visit, for: node)
    visitIfEnabled(NoForceTry.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(NoGuardInTests.visit, for: node)
    visitIfEnabled(RedundantReturn.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(UnusedArguments.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ClosureExprSyntax) {
    onVisitPost(rule: EmptyBraces.self, for: node)
    onVisitPost(rule: NoEmptyLinesOpeningClosingBraces.self, for: node)
    onVisitPost(rule: NoForceTry.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: NoGuardInTests.self, for: node)
    onVisitPost(rule: RedundantReturn.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: UnusedArguments.self, for: node)
  }

  override func visit(_ node: ClosureParameterSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ClosureParameterSyntax) {
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: ClosureSignatureSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(PreferVoidReturn.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ClosureSignatureSyntax) {
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: PreferVoidReturn.self, for: node)
  }

  override func visit(_ node: CodeBlockItemListSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(EmptyExtensions.visit, for: node)
    visitIfEnabled(NoAssignmentInExpressions.visit, for: node)
    visitIfEnabled(NoGuardInTests.visit, for: node)
    visitIfEnabled(NoSemicolons.visit, for: node)
    visitIfEnabled(OneDeclarationPerLine.visit, for: node)
    visitIfEnabled(PreferConditionalExpression.visit, for: node)
    visitIfEnabled(PreferEarlyExits.visit, for: node)
    visitIfEnabled(RedundantLet.visit, for: node)
    visitIfEnabled(RedundantProperty.visit, for: node)
    visitIfEnabled(SortDeclarations.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: CodeBlockItemListSyntax) {
    onVisitPost(rule: EmptyExtensions.self, for: node)
    onVisitPost(rule: NoAssignmentInExpressions.self, for: node)
    onVisitPost(rule: NoGuardInTests.self, for: node)
    onVisitPost(rule: NoSemicolons.self, for: node)
    onVisitPost(rule: OneDeclarationPerLine.self, for: node)
    onVisitPost(rule: PreferConditionalExpression.self, for: node)
    onVisitPost(rule: PreferEarlyExits.self, for: node)
    onVisitPost(rule: RedundantLet.self, for: node)
    onVisitPost(rule: RedundantProperty.self, for: node)
    onVisitPost(rule: SortDeclarations.self, for: node)
  }

  override func visit(_ node: CodeBlockItemSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocComments.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: CodeBlockItemSyntax) {
    onVisitPost(rule: DocComments.self, for: node)
  }

  override func visit(_ node: CodeBlockSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(AmbiguousTrailingClosureOverload.visit, for: node)
    visitIfEnabled(BlankLinesAfterGuardStatements.visit, for: node)
    visitIfEnabled(EmptyBraces.visit, for: node)
    visitIfEnabled(NoEmptyLinesOpeningClosingBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: CodeBlockSyntax) {
    onVisitPost(rule: AmbiguousTrailingClosureOverload.self, for: node)
    onVisitPost(rule: BlankLinesAfterGuardStatements.self, for: node)
    onVisitPost(rule: EmptyBraces.self, for: node)
    onVisitPost(rule: NoEmptyLinesOpeningClosingBraces.self, for: node)
  }

  override func visit(_ node: ConditionElementListSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PreferCommaConditions.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ConditionElementListSyntax) {
    onVisitPost(rule: PreferCommaConditions.self, for: node)
  }

  override func visit(_ node: ConditionElementSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(ExplicitNilCheck.visit, for: node)
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ConditionElementSyntax) {
    onVisitPost(rule: ExplicitNilCheck.self, for: node)
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
  }

  override func visit(_ node: DeinitializerDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: DeinitializerDeclSyntax) {
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: DoStmtSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: DoStmtSyntax) {
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: EnumCaseDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(RedundantRawValues.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: EnumCaseDeclSyntax) {
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: RedundantRawValues.self, for: node)
  }

  override func visit(_ node: EnumCaseElementSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: EnumCaseElementSyntax) {
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: EnumCaseParameterSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: EnumCaseParameterSyntax) {
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: EnumDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(FullyIndirectEnum.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    visitIfEnabled(OneDeclarationPerLine.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantSendable.visit, for: node)
    visitIfEnabled(RedundantSwiftTestingSuite.visit, for: node)
    visitIfEnabled(SimplifyGenericConstraints.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(ValidateTestCases.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: EnumDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: FullyIndirectEnum.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
    onVisitPost(rule: OneDeclarationPerLine.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantSendable.self, for: node)
    onVisitPost(rule: RedundantSwiftTestingSuite.self, for: node)
    onVisitPost(rule: SimplifyGenericConstraints.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: ValidateTestCases.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoRetroactiveConformances.visit, for: node)
    visitIfEnabled(PreferAngleBracketExtensions.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ExtensionDeclSyntax) {
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoRetroactiveConformances.self, for: node)
    onVisitPost(rule: PreferAngleBracketExtensions.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: ForStmtSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PatternLetPlacement.visit, for: node)
    visitIfEnabled(PreferWhereClausesInForLoops.visit, for: node)
    visitIfEnabled(UnusedArguments.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ForStmtSyntax) {
    onVisitPost(rule: PatternLetPlacement.self, for: node)
    onVisitPost(rule: PreferWhereClausesInForLoops.self, for: node)
    onVisitPost(rule: UnusedArguments.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: ForceUnwrapExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(URLMacro.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ForceUnwrapExprSyntax) {
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: URLMacro.self, for: node)
  }

  override func visit(_ node: FunctionCallExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(HoistAwait.visit, for: node)
    visitIfEnabled(HoistTry.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(NoTrailingClosureParens.visit, for: node)
    visitIfEnabled(OnlyOneTrailingClosureArgument.visit, for: node)
    visitIfEnabled(PreferAssertionFailure.visit, for: node)
    visitIfEnabled(PreferKeyPath.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(PreferTrailingClosures.visit, for: node)
    visitIfEnabled(RedundantClosure.visit, for: node)
    visitIfEnabled(RedundantInit.visit, for: node)
    visitIfEnabled(ReplaceForEachWithForLoop.visit, for: node)
    visitIfEnabled(WrapMultilineFunctionChains.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: FunctionCallExprSyntax) {
    onVisitPost(rule: HoistAwait.self, for: node)
    onVisitPost(rule: HoistTry.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: NoTrailingClosureParens.self, for: node)
    onVisitPost(rule: OnlyOneTrailingClosureArgument.self, for: node)
    onVisitPost(rule: PreferAssertionFailure.self, for: node)
    onVisitPost(rule: PreferKeyPath.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: PreferTrailingClosures.self, for: node)
    onVisitPost(rule: RedundantClosure.self, for: node)
    onVisitPost(rule: RedundantInit.self, for: node)
    onVisitPost(rule: ReplaceForEachWithForLoop.self, for: node)
    onVisitPost(rule: WrapMultilineFunctionChains.self, for: node)
  }

  override func visit(_ node: FunctionDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExplicitOwnership.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoForceTry.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(NoGuardInTests.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    visitIfEnabled(OpaqueGenericParameters.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantAsync.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantReturn.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantThrows.visit, for: node)
    visitIfEnabled(RedundantViewBuilder.visit, for: node)
    visitIfEnabled(SimplifyGenericConstraints.visit, for: node)
    visitIfEnabled(SwiftTestingTestCaseNames.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(UnusedArguments.visit, for: node)
    visitIfEnabled(ValidateDocumentationComments.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: FunctionDeclSyntax) {
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExplicitOwnership.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoForceTry.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: NoGuardInTests.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
    onVisitPost(rule: OpaqueGenericParameters.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantAsync.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantReturn.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantThrows.self, for: node)
    onVisitPost(rule: RedundantViewBuilder.self, for: node)
    onVisitPost(rule: SimplifyGenericConstraints.self, for: node)
    onVisitPost(rule: SwiftTestingTestCaseNames.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: UnusedArguments.self, for: node)
    onVisitPost(rule: ValidateDocumentationComments.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: FunctionEffectSpecifiersSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(RedundantTypedThrows.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: FunctionEffectSpecifiersSyntax) {
    onVisitPost(rule: RedundantTypedThrows.self, for: node)
  }

  override func visit(_ node: FunctionParameterSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(EmptyCollectionLiteral.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: FunctionParameterSyntax) {
    onVisitPost(rule: EmptyCollectionLiteral.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: FunctionSignatureSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoVoidReturnOnFunctionSignature.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: FunctionSignatureSyntax) {
    onVisitPost(rule: NoVoidReturnOnFunctionSignature.self, for: node)
  }

  override func visit(_ node: FunctionTypeSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PreferVoidReturn.visit, for: node)
    visitIfEnabled(RedundantTypedThrows.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: FunctionTypeSyntax) {
    onVisitPost(rule: PreferVoidReturn.self, for: node)
    onVisitPost(rule: RedundantTypedThrows.self, for: node)
  }

  override func visit(_ node: GenericParameterSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: GenericParameterSyntax) {
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: GenericSpecializationExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PreferShorthandTypeNames.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: GenericSpecializationExprSyntax) {
    onVisitPost(rule: PreferShorthandTypeNames.self, for: node)
  }

  override func visit(_ node: GuardStmtSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: GuardStmtSyntax) {
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: IdentifierPatternSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(ASCIIIdentifiers.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: IdentifierPatternSyntax) {
    onVisitPost(rule: ASCIIIdentifiers.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: IdentifierTypeSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PreferShorthandTypeNames.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: IdentifierTypeSyntax) {
    onVisitPost(rule: PreferShorthandTypeNames.self, for: node)
  }

  override func visit(_ node: IfExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: IfExprSyntax) {
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: ImportDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoForceTry.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(NoGuardInTests.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(RedundantSwiftTestingSuite.visit, for: node)
    visitIfEnabled(URLMacro.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ImportDeclSyntax) {
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoForceTry.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: NoGuardInTests.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: RedundantSwiftTestingSuite.self, for: node)
    onVisitPost(rule: URLMacro.self, for: node)
  }

  override func visit(_ node: InfixOperatorExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoAssignmentInExpressions.visit, for: node)
    visitIfEnabled(NoYodaConditions.visit, for: node)
    visitIfEnabled(PreferIsEmpty.visit, for: node)
    visitIfEnabled(WrapConditionalAssignment.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: InfixOperatorExprSyntax) {
    onVisitPost(rule: NoAssignmentInExpressions.self, for: node)
    onVisitPost(rule: NoYodaConditions.self, for: node)
    onVisitPost(rule: PreferIsEmpty.self, for: node)
    onVisitPost(rule: WrapConditionalAssignment.self, for: node)
  }

  override func visit(_ node: InitializerClauseSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: InitializerClauseSyntax) {
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
  }

  override func visit(_ node: InitializerDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(InitCoderUnavailable.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(OpaqueGenericParameters.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(UnusedArguments.visit, for: node)
    visitIfEnabled(ValidateDocumentationComments.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: InitializerDeclSyntax) {
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: InitCoderUnavailable.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: OpaqueGenericParameters.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: UnusedArguments.self, for: node)
    onVisitPost(rule: ValidateDocumentationComments.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: IntegerLiteralExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(GroupNumericLiterals.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: IntegerLiteralExprSyntax) {
    onVisitPost(rule: GroupNumericLiterals.self, for: node)
  }

  override func visit(_ node: LabeledExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(RedundantLet.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: LabeledExprSyntax) {
    onVisitPost(rule: RedundantLet.self, for: node)
  }

  override func visit(_ node: MacroExpansionExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoPlaygroundLiterals.visit, for: node)
    visitIfEnabled(PreferFileID.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: MacroExpansionExprSyntax) {
    onVisitPost(rule: NoPlaygroundLiterals.self, for: node)
    onVisitPost(rule: PreferFileID.self, for: node)
  }

  override func visit(_ node: MatchingPatternConditionSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PatternLetPlacement.visit, for: node)
    visitIfEnabled(RedundantPattern.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: MatchingPatternConditionSyntax) {
    onVisitPost(rule: PatternLetPlacement.self, for: node)
    onVisitPost(rule: RedundantPattern.self, for: node)
  }

  override func visit(_ node: MemberAccessExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(BlankLinesBetweenChainedFunctions.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(PreferCountWhere.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantStaticSelf.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: MemberAccessExprSyntax) {
    onVisitPost(rule: BlankLinesBetweenChainedFunctions.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: PreferCountWhere.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantStaticSelf.self, for: node)
  }

  override func visit(_ node: MemberBlockItemListSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoSemicolons.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(SortDeclarations.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: MemberBlockItemListSyntax) {
    onVisitPost(rule: NoSemicolons.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: SortDeclarations.self, for: node)
  }

  override func visit(_ node: MemberBlockItemSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocComments.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: MemberBlockItemSyntax) {
    onVisitPost(rule: DocComments.self, for: node)
  }

  override func visit(_ node: MemberBlockSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(AmbiguousTrailingClosureOverload.visit, for: node)
    visitIfEnabled(BlankLinesBetweenScopes.visit, for: node)
    visitIfEnabled(EmptyBraces.visit, for: node)
    visitIfEnabled(NoEmptyLinesOpeningClosingBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: MemberBlockSyntax) {
    onVisitPost(rule: AmbiguousTrailingClosureOverload.self, for: node)
    onVisitPost(rule: BlankLinesBetweenScopes.self, for: node)
    onVisitPost(rule: EmptyBraces.self, for: node)
    onVisitPost(rule: NoEmptyLinesOpeningClosingBraces.self, for: node)
  }

  override func visit(_ node: OptionalBindingConditionSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(NoBacktickedSelf.visit, for: node)
    visitIfEnabled(RedundantOptionalBinding.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: OptionalBindingConditionSyntax) {
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: NoBacktickedSelf.self, for: node)
    onVisitPost(rule: RedundantOptionalBinding.self, for: node)
  }

  override func visit(_ node: PatternBindingSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(EmptyCollectionLiteral.visit, for: node)
    visitIfEnabled(PreferSingleLinePropertyGetter.visit, for: node)
    visitIfEnabled(RedundantReturn.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapConditionalAssignment.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: PatternBindingSyntax) {
    onVisitPost(rule: EmptyCollectionLiteral.self, for: node)
    onVisitPost(rule: PreferSingleLinePropertyGetter.self, for: node)
    onVisitPost(rule: RedundantReturn.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapConditionalAssignment.self, for: node)
  }

  override func visit(_ node: PrecedenceGroupDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoEmptyLinesOpeningClosingBraces.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: PrecedenceGroupDeclSyntax) {
    onVisitPost(rule: NoEmptyLinesOpeningClosingBraces.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
  }

  override func visit(_ node: PrefixOperatorExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PreferExplicitFalse.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: PrefixOperatorExprSyntax) {
    onVisitPost(rule: PreferExplicitFalse.self, for: node)
  }

  override func visit(_ node: ProtocolDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    visitIfEnabled(PreferAnyObject.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ProtocolDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
    onVisitPost(rule: PreferAnyObject.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: RepeatStmtSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: RepeatStmtSyntax) {
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
  }

  override func visit(_ node: ReturnStmtSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: ReturnStmtSyntax) {
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
  }

  override func visit(_ node: SourceFileSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(AmbiguousTrailingClosureOverload.visit, for: node)
    visitIfEnabled(BlankLinesAfterImports.visit, for: node)
    visitIfEnabled(BlankLinesBetweenImports.visit, for: node)
    visitIfEnabled(BlankLinesBetweenScopes.visit, for: node)
    visitIfEnabled(FileHeader.visit, for: node)
    visitIfEnabled(FileScopedDeclarationPrivacy.visit, for: node)
    visitIfEnabled(LinebreakAtEndOfFile.visit, for: node)
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(NoForceTry.visit, for: node)
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    visitIfEnabled(NoGuardInTests.visit, for: node)
    visitIfEnabled(NoImplicitlyUnwrappedOptionals.visit, for: node)
    visitIfEnabled(PreferEnvironmentEntry.visit, for: node)
    visitIfEnabled(PreferFinalClasses.visit, for: node)
    visitIfEnabled(PreferSwiftTesting.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(SortImports.visit, for: node)
    visitIfEnabled(SwiftTestingTestCaseNames.visit, for: node)
    visitIfEnabled(TestSuiteAccessControl.visit, for: node)
    visitIfEnabled(URLMacro.visit, for: node)
    visitIfEnabled(ValidateTestCases.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SourceFileSyntax) {
    onVisitPost(rule: AmbiguousTrailingClosureOverload.self, for: node)
    onVisitPost(rule: BlankLinesAfterImports.self, for: node)
    onVisitPost(rule: BlankLinesBetweenImports.self, for: node)
    onVisitPost(rule: BlankLinesBetweenScopes.self, for: node)
    onVisitPost(rule: FileHeader.self, for: node)
    onVisitPost(rule: FileScopedDeclarationPrivacy.self, for: node)
    onVisitPost(rule: LinebreakAtEndOfFile.self, for: node)
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: NoForceTry.self, for: node)
    onVisitPost(rule: NoForceUnwrap.self, for: node)
    onVisitPost(rule: NoGuardInTests.self, for: node)
    onVisitPost(rule: NoImplicitlyUnwrappedOptionals.self, for: node)
    onVisitPost(rule: PreferEnvironmentEntry.self, for: node)
    onVisitPost(rule: PreferFinalClasses.self, for: node)
    onVisitPost(rule: PreferSwiftTesting.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: SortImports.self, for: node)
    onVisitPost(rule: SwiftTestingTestCaseNames.self, for: node)
    onVisitPost(rule: TestSuiteAccessControl.self, for: node)
    onVisitPost(rule: URLMacro.self, for: node)
    onVisitPost(rule: ValidateTestCases.self, for: node)
  }

  override func visit(_ node: StringLiteralExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: StringLiteralExprSyntax) {
    onVisitPost(rule: NoForceUnwrap.self, for: node)
  }

  override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(EnumNamespaces.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    visitIfEnabled(PreferSynthesizedInitializer.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantEquatable.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantSendable.visit, for: node)
    visitIfEnabled(RedundantSwiftTestingSuite.visit, for: node)
    visitIfEnabled(SimplifyGenericConstraints.visit, for: node)
    visitIfEnabled(TestSuiteAccessControl.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(ValidateTestCases.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: StructDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: EnumNamespaces.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
    onVisitPost(rule: PreferSynthesizedInitializer.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantEquatable.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantSendable.self, for: node)
    onVisitPost(rule: RedundantSwiftTestingSuite.self, for: node)
    onVisitPost(rule: SimplifyGenericConstraints.self, for: node)
    onVisitPost(rule: TestSuiteAccessControl.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: ValidateTestCases.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: SubscriptCallExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoForceUnwrap.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SubscriptCallExprSyntax) {
    onVisitPost(rule: NoForceUnwrap.self, for: node)
  }

  override func visit(_ node: SubscriptDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(OpaqueGenericParameters.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantReturn.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    visitIfEnabled(UnusedArguments.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SubscriptDeclSyntax) {
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: OpaqueGenericParameters.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantReturn.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
    onVisitPost(rule: UnusedArguments.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
  }

  override func visit(_ node: SwitchCaseItemSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(PatternLetPlacement.visit, for: node)
    visitIfEnabled(RedundantPattern.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SwitchCaseItemSyntax) {
    onVisitPost(rule: PatternLetPlacement.self, for: node)
    onVisitPost(rule: RedundantPattern.self, for: node)
  }

  override func visit(_ node: SwitchCaseLabelSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoLabelsInCasePatterns.visit, for: node)
    visitIfEnabled(WrapSwitchCases.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SwitchCaseLabelSyntax) {
    onVisitPost(rule: NoLabelsInCasePatterns.self, for: node)
    onVisitPost(rule: WrapSwitchCases.self, for: node)
  }

  override func visit(_ node: SwitchCaseListSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoFallthroughOnlyCases.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SwitchCaseListSyntax) {
    onVisitPost(rule: NoFallthroughOnlyCases.self, for: node)
  }

  override func visit(_ node: SwitchCaseSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(RedundantBreak.visit, for: node)
    visitIfEnabled(SortSwitchCases.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SwitchCaseSyntax) {
    onVisitPost(rule: RedundantBreak.self, for: node)
    onVisitPost(rule: SortSwitchCases.self, for: node)
  }

  override func visit(_ node: SwitchExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(BlankLinesAfterSwitchCase.visit, for: node)
    visitIfEnabled(ConsistentSwitchCaseSpacing.visit, for: node)
    visitIfEnabled(NoEmptyLinesOpeningClosingBraces.visit, for: node)
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: SwitchExprSyntax) {
    onVisitPost(rule: BlankLinesAfterSwitchCase.self, for: node)
    onVisitPost(rule: ConsistentSwitchCaseSpacing.self, for: node)
    onVisitPost(rule: NoEmptyLinesOpeningClosingBraces.self, for: node)
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }

  override func visit(_ node: TokenSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(BlankLinesAroundMark.visit, for: node)
    visitIfEnabled(CapitalizeAcronyms.visit, for: node)
    visitIfEnabled(FormatSpecialComments.visit, for: node)
    visitIfEnabled(LeadingDotOperators.visit, for: node)
    visitIfEnabled(NoBlockComments.visit, for: node)
    visitIfEnabled(RedundantBackticks.visit, for: node)
    visitIfEnabled(WrapSingleLineComments.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: TokenSyntax) {
    onVisitPost(rule: BlankLinesAroundMark.self, for: node)
    onVisitPost(rule: CapitalizeAcronyms.self, for: node)
    onVisitPost(rule: FormatSpecialComments.self, for: node)
    onVisitPost(rule: LeadingDotOperators.self, for: node)
    onVisitPost(rule: NoBlockComments.self, for: node)
    onVisitPost(rule: RedundantBackticks.self, for: node)
    onVisitPost(rule: WrapSingleLineComments.self, for: node)
  }

  override func visit(_ node: TryExprSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoForceTry.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: TryExprSyntax) {
    onVisitPost(rule: NoForceTry.self, for: node)
  }

  override func visit(_ node: TypeAliasDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(CapitalizedTypeNames.visit, for: node)
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoLeadingUnderscores.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(SortTypealiases.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: TypeAliasDeclSyntax) {
    onVisitPost(rule: CapitalizedTypeNames.self, for: node)
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoLeadingUnderscores.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: SortTypealiases.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
  }

  override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(DocCommentSummary.visit, for: node)
    visitIfEnabled(DocCommentsBeforeModifiers.visit, for: node)
    visitIfEnabled(DocumentPublicDeclarations.visit, for: node)
    visitIfEnabled(LowerCamelCase.visit, for: node)
    visitIfEnabled(ModifierOrder.visit, for: node)
    visitIfEnabled(ModifiersOnSameLine.visit, for: node)
    visitIfEnabled(NoExtensionAccessLevel.visit, for: node)
    visitIfEnabled(NoImplicitlyUnwrappedOptionals.visit, for: node)
    visitIfEnabled(NoTypeRepetitionInStaticProperties.visit, for: node)
    visitIfEnabled(PrivateStateVariables.visit, for: node)
    visitIfEnabled(RedundantAccessControl.visit, for: node)
    visitIfEnabled(RedundantNilInit.visit, for: node)
    visitIfEnabled(RedundantObjc.visit, for: node)
    visitIfEnabled(RedundantPattern.visit, for: node)
    visitIfEnabled(RedundantSelf.visit, for: node)
    visitIfEnabled(RedundantType.visit, for: node)
    visitIfEnabled(RedundantViewBuilder.visit, for: node)
    visitIfEnabled(StrongOutlets.visit, for: node)
    visitIfEnabled(TripleSlashDocComments.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: VariableDeclSyntax) {
    onVisitPost(rule: DocCommentSummary.self, for: node)
    onVisitPost(rule: DocCommentsBeforeModifiers.self, for: node)
    onVisitPost(rule: DocumentPublicDeclarations.self, for: node)
    onVisitPost(rule: LowerCamelCase.self, for: node)
    onVisitPost(rule: ModifierOrder.self, for: node)
    onVisitPost(rule: ModifiersOnSameLine.self, for: node)
    onVisitPost(rule: NoExtensionAccessLevel.self, for: node)
    onVisitPost(rule: NoImplicitlyUnwrappedOptionals.self, for: node)
    onVisitPost(rule: NoTypeRepetitionInStaticProperties.self, for: node)
    onVisitPost(rule: PrivateStateVariables.self, for: node)
    onVisitPost(rule: RedundantAccessControl.self, for: node)
    onVisitPost(rule: RedundantNilInit.self, for: node)
    onVisitPost(rule: RedundantObjc.self, for: node)
    onVisitPost(rule: RedundantPattern.self, for: node)
    onVisitPost(rule: RedundantSelf.self, for: node)
    onVisitPost(rule: RedundantType.self, for: node)
    onVisitPost(rule: RedundantViewBuilder.self, for: node)
    onVisitPost(rule: StrongOutlets.self, for: node)
    onVisitPost(rule: TripleSlashDocComments.self, for: node)
  }

  override func visit(_ node: WhileStmtSyntax) -> SyntaxVisitorContinueKind {
    visitIfEnabled(NoParensAroundConditions.visit, for: node)
    visitIfEnabled(WrapBodies.visit, for: node)
    visitIfEnabled(WrapMultilineStatementBraces.visit, for: node)
    return .visitChildren
  }
  override func visitPost(_ node: WhileStmtSyntax) {
    onVisitPost(rule: NoParensAroundConditions.self, for: node)
    onVisitPost(rule: WrapBodies.self, for: node)
    onVisitPost(rule: WrapMultilineStatementBraces.self, for: node)
  }
}

extension FormatPipeline {

  func rewrite(_ node: Syntax) -> Syntax {
    var node = node
    node = BlankLinesAfterGuardStatements(context: context).rewrite(node)
    node = BlankLinesAfterImports(context: context).rewrite(node)
    node = BlankLinesAfterSwitchCase(context: context).rewrite(node)
    node = BlankLinesAroundMark(context: context).rewrite(node)
    node = BlankLinesBetweenChainedFunctions(context: context).rewrite(node)
    node = BlankLinesBetweenImports(context: context).rewrite(node)
    node = BlankLinesBetweenScopes(context: context).rewrite(node)
    node = CapitalizeAcronyms(context: context).rewrite(node)
    node = ConsistentSwitchCaseSpacing(context: context).rewrite(node)
    node = DocComments(context: context).rewrite(node)
    node = DocCommentsBeforeModifiers(context: context).rewrite(node)
    node = EmptyBraces(context: context).rewrite(node)
    node = EmptyCollectionLiteral(context: context).rewrite(node)
    node = EmptyExtensions(context: context).rewrite(node)
    node = EnumNamespaces(context: context).rewrite(node)
    node = ExplicitNilCheck(context: context).rewrite(node)
    node = FileHeader(context: context).rewrite(node)
    node = FileScopedDeclarationPrivacy(context: context).rewrite(node)
    node = FormatSpecialComments(context: context).rewrite(node)
    node = FullyIndirectEnum(context: context).rewrite(node)
    node = GroupNumericLiterals(context: context).rewrite(node)
    node = HoistAwait(context: context).rewrite(node)
    node = HoistTry(context: context).rewrite(node)
    node = InitCoderUnavailable(context: context).rewrite(node)
    node = LeadingDotOperators(context: context).rewrite(node)
    node = LinebreakAtEndOfFile(context: context).rewrite(node)
    node = ModifierOrder(context: context).rewrite(node)
    node = ModifiersOnSameLine(context: context).rewrite(node)
    node = NoAssignmentInExpressions(context: context).rewrite(node)
    node = NoBacktickedSelf(context: context).rewrite(node)
    node = NoEmptyLinesOpeningClosingBraces(context: context).rewrite(node)
    node = NoExplicitOwnership(context: context).rewrite(node)
    node = NoExtensionAccessLevel(context: context).rewrite(node)
    node = NoFallthroughOnlyCases(context: context).rewrite(node)
    node = NoForceTry(context: context).rewrite(node)
    node = NoForceUnwrap(context: context).rewrite(node)
    node = NoGuardInTests(context: context).rewrite(node)
    node = NoLabelsInCasePatterns(context: context).rewrite(node)
    node = NoParensAroundConditions(context: context).rewrite(node)
    node = NoSemicolons(context: context).rewrite(node)
    node = NoTrailingClosureParens(context: context).rewrite(node)
    node = NoVoidReturnOnFunctionSignature(context: context).rewrite(node)
    node = NoYodaConditions(context: context).rewrite(node)
    node = OneDeclarationPerLine(context: context).rewrite(node)
    node = OpaqueGenericParameters(context: context).rewrite(node)
    node = PatternLetPlacement(context: context).rewrite(node)
    node = PreferAngleBracketExtensions(context: context).rewrite(node)
    node = PreferAnyObject(context: context).rewrite(node)
    node = PreferAssertionFailure(context: context).rewrite(node)
    node = PreferCommaConditions(context: context).rewrite(node)
    node = PreferConditionalExpression(context: context).rewrite(node)
    node = PreferCountWhere(context: context).rewrite(node)
    node = PreferEarlyExits(context: context).rewrite(node)
    node = PreferEnvironmentEntry(context: context).rewrite(node)
    node = PreferExplicitFalse(context: context).rewrite(node)
    node = PreferFileID(context: context).rewrite(node)
    node = PreferFinalClasses(context: context).rewrite(node)
    node = PreferIsEmpty(context: context).rewrite(node)
    node = PreferKeyPath(context: context).rewrite(node)
    node = PreferMainAttribute(context: context).rewrite(node)
    node = PreferShorthandTypeNames(context: context).rewrite(node)
    node = PreferSingleLinePropertyGetter(context: context).rewrite(node)
    node = PreferSwiftTesting(context: context).rewrite(node)
    node = PreferTrailingClosures(context: context).rewrite(node)
    node = PreferVoidReturn(context: context).rewrite(node)
    node = PreferWhereClausesInForLoops(context: context).rewrite(node)
    node = PrivateStateVariables(context: context).rewrite(node)
    node = RedundantAccessControl(context: context).rewrite(node)
    node = RedundantAsync(context: context).rewrite(node)
    node = RedundantBackticks(context: context).rewrite(node)
    node = RedundantBreak(context: context).rewrite(node)
    node = RedundantClosure(context: context).rewrite(node)
    node = RedundantEquatable(context: context).rewrite(node)
    node = RedundantInit(context: context).rewrite(node)
    node = RedundantLet(context: context).rewrite(node)
    node = RedundantLetError(context: context).rewrite(node)
    node = RedundantNilInit(context: context).rewrite(node)
    node = RedundantObjc(context: context).rewrite(node)
    node = RedundantOptionalBinding(context: context).rewrite(node)
    node = RedundantPattern(context: context).rewrite(node)
    node = RedundantProperty(context: context).rewrite(node)
    node = RedundantRawValues(context: context).rewrite(node)
    node = RedundantReturn(context: context).rewrite(node)
    node = RedundantSelf(context: context).rewrite(node)
    node = RedundantSendable(context: context).rewrite(node)
    node = RedundantStaticSelf(context: context).rewrite(node)
    node = RedundantSwiftTestingSuite(context: context).rewrite(node)
    node = RedundantThrows(context: context).rewrite(node)
    node = RedundantType(context: context).rewrite(node)
    node = RedundantTypedThrows(context: context).rewrite(node)
    node = RedundantViewBuilder(context: context).rewrite(node)
    node = SimplifyGenericConstraints(context: context).rewrite(node)
    node = SortDeclarations(context: context).rewrite(node)
    node = SortImports(context: context).rewrite(node)
    node = SortSwitchCases(context: context).rewrite(node)
    node = SortTypealiases(context: context).rewrite(node)
    node = StrongOutlets(context: context).rewrite(node)
    node = SwiftTestingTestCaseNames(context: context).rewrite(node)
    node = TestSuiteAccessControl(context: context).rewrite(node)
    node = TripleSlashDocComments(context: context).rewrite(node)
    node = URLMacro(context: context).rewrite(node)
    node = UnusedArguments(context: context).rewrite(node)
    node = ValidateTestCases(context: context).rewrite(node)
    node = WrapBodies(context: context).rewrite(node)
    node = WrapConditionalAssignment(context: context).rewrite(node)
    node = WrapMultilineFunctionChains(context: context).rewrite(node)
    node = WrapMultilineStatementBraces(context: context).rewrite(node)
    node = WrapSingleLineComments(context: context).rewrite(node)
    node = WrapSwitchCases(context: context).rewrite(node)
    return node
  }
}
