import Foundation

/// Generates the LintPipeline.generated.swift file
enum PipelineEmitter {
  static func emit(rules: [RuleInfo]) -> String {
    // Collect all node types across all rules
    var allVisitNodeTypes: Set<String> = []
    var allVisitPostNodeTypes: Set<String> = []

    for rule in rules {
      for nodeType in rule.visitNodeTypes {
        allVisitNodeTypes.insert(nodeType)
      }
      for nodeType in rule.visitPostNodeTypes {
        allVisitPostNodeTypes.insert(nodeType)
      }
    }

    // The 10 declaration types that ViolationCollectingVisitor handles for
    // skippableDeclarations — the pipeline must generate skip depth tracking for these
    let skippableDeclTypes: [String] = [
      "ActorDeclSyntax", "ClassDeclSyntax", "EnumDeclSyntax",
      "ExtensionDeclSyntax", "FunctionDeclSyntax", "InitializerDeclSyntax",
      "ProtocolDeclSyntax", "StructDeclSyntax", "SubscriptDeclSyntax",
      "VariableDeclSyntax",
    ]

    // Ensure all skippable decl types appear in both visit and visitPost
    for declType in skippableDeclTypes {
      allVisitNodeTypes.insert(declType)
      allVisitPostNodeTypes.insert(declType)
    }

    // Node types that have rule-specific visit() overrides need corresponding
    // visitPost() methods to manage the visit-return skip stack
    let ruleVisitNodeTypes = Set(rules.flatMap(\.visitNodeTypes))
    for nodeType in ruleVisitNodeTypes {
      allVisitPostNodeTypes.insert(nodeType)
    }

    let sortedVisitNodeTypes = allVisitNodeTypes.sorted()
    let sortedVisitPostNodeTypes = allVisitPostNodeTypes.sorted()
    let sortedRuleIDs = Set(rules.map(\.ruleID)).sorted()

    // Merge rules with the same ID (e.g. from multiple visitor classes)
    var mergedRules: [String: (visitNodeTypes: Set<String>, visitPostNodeTypes: Set<String>)] =
      [:]
    for rule in rules {
      var existing = mergedRules[rule.ruleID] ?? (visitNodeTypes: [], visitPostNodeTypes: [])
      existing.visitNodeTypes.formUnion(rule.visitNodeTypes)
      existing.visitPostNodeTypes.formUnion(rule.visitPostNodeTypes)
      mergedRules[rule.ruleID] = existing
    }

    var out = ""

    out += "// Generated by GeneratePipeline — do not edit manually\n"
    out += "// swiftlint:disable all\n"
    out += "// sm:disable all\n"
    out += "import SwiftiomaticSyntax\n\n"

    // Eligible rule IDs set
    out += "let pipelineEligibleRuleIDs: Set<String> = [\n"
    for id in sortedRuleIDs {
      out += "    \"\(id)\",\n"
    }
    out += "]\n\n"

    // LintPipeline class
    out += "final class LintPipeline: SyntaxVisitor {\n"
    out += "    private var visitors: [SyntaxVisitor] = []\n"
    out += "    private var visitorProtocols: [ViolationCollectingVisitorProtocol] = []\n"
    out += "    private var skipDepths: [Int] = []\n"
    out += "    private var skipSets: [[any DeclSyntaxProtocol.Type]] = []\n"
    out += "    /// Stack tracking which visitors returned .skipChildren from visit()\n"
    out += "    private var visitSkipStack: [[Int]] = []\n\n"

    // Per-node-type dispatch arrays
    for nodeType in sortedVisitNodeTypes {
      let varName = propertyName(for: nodeType, kind: "visit")
      out += "    private var \(varName): [Int] = []\n"
    }
    out += "\n"
    for nodeType in sortedVisitPostNodeTypes {
      let varName = propertyName(for: nodeType, kind: "visitPost")
      out += "    private var \(varName): [Int] = []\n"
    }
    out += "\n"

    // Init
    out +=
      "    init(visitors: [(id: String, visitor: SyntaxVisitor & ViolationCollectingVisitorProtocol)]) {\n"
    out += "        super.init(viewMode: .sourceAccurate)\n"
    out += "        for (idx, entry) in visitors.enumerated() {\n"
    out += "            self.visitors.append(entry.visitor)\n"
    out += "            self.visitorProtocols.append(entry.visitor)\n"
    out += "            self.skipSets.append(entry.visitor.skippableDeclarations)\n"
    out += "            switch entry.id {\n"

    for ruleID in mergedRules.keys.sorted() {
      let merged = mergedRules[ruleID]!
      out += "            case \"\(ruleID)\":\n"
      for nodeType in merged.visitNodeTypes.sorted() {
        let varName = propertyName(for: nodeType, kind: "visit")
        out += "                \(varName).append(idx)\n"
      }
      for nodeType in merged.visitPostNodeTypes.sorted() {
        let varName = propertyName(for: nodeType, kind: "visitPost")
        out += "                \(varName).append(idx)\n"
      }
      out += "\n"
    }

    out += "            default:\n"
    out += "                break\n"
    out += "            }\n"
    out += "        }\n"
    out += "        self.skipDepths = Array(repeating: 0, count: visitors.count)\n"
    out += "    }\n\n"

    // Generate visit() methods
    for nodeType in sortedVisitNodeTypes {
      let varName_visit = propertyName(for: nodeType, kind: "visit")
      let isSkippableDecl = skippableDeclTypes.contains(nodeType)
      let hasRuleVisitOverrides = ruleVisitNodeTypes.contains(nodeType)

      out += "    override func visit(_ node: \(nodeType)) -> SyntaxVisitorContinueKind {\n"

      if isSkippableDecl {
        out += "        for idx in 0..<visitors.count {\n"
        out += "            if skipSets[idx].contains(where: { $0 == \(nodeType).self }) {\n"
        out += "                skipDepths[idx] += 1\n"
        out += "            }\n"
        out += "        }\n"
      }

      if hasRuleVisitOverrides {
        out += "        var skippedByReturn: [Int] = []\n"
        out += "        for idx in \(varName_visit) where skipDepths[idx] == 0 {\n"
        out += "            if visitors[idx].visit(node) == .skipChildren {\n"
        out += "                skipDepths[idx] += 1\n"
        out += "                skippedByReturn.append(idx)\n"
        out += "            }\n"
        out += "        }\n"
        out += "        visitSkipStack.append(skippedByReturn)\n"
      }

      out += "        return .visitChildren\n"
      out += "    }\n\n"
    }

    // Generate visitPost() methods
    for nodeType in sortedVisitPostNodeTypes {
      let varName_visitPost = propertyName(for: nodeType, kind: "visitPost")
      let isSkippableDecl = skippableDeclTypes.contains(nodeType)
      let hasRuleVisitOverrides = ruleVisitNodeTypes.contains(nodeType)

      out += "    override func visitPost(_ node: \(nodeType)) {\n"

      // Pop visit-return skip stack BEFORE calling visitPost overrides
      // so that the visitor can receive its own visitPost for the node
      // whose visit() it returned .skipChildren from
      if hasRuleVisitOverrides {
        out += "        if let skippedByReturn = visitSkipStack.popLast() {\n"
        out += "            for idx in skippedByReturn {\n"
        out += "                skipDepths[idx] -= 1\n"
        out += "            }\n"
        out += "        }\n"
      }

      out += "        for idx in \(varName_visitPost) where skipDepths[idx] == 0 {\n"
      out += "            visitors[idx].visitPost(node)\n"
      out += "        }\n"

      if isSkippableDecl {
        out += "        for idx in 0..<visitors.count {\n"
        out += "            if skipSets[idx].contains(where: { $0 == \(nodeType).self }) {\n"
        out += "                skipDepths[idx] -= 1\n"
        out += "            }\n"
        out += "        }\n"
      }

      out += "    }\n\n"
    }

    // collectViolations method
    out += "    func collectViolations() -> [(index: Int, violations: [SyntaxViolation])] {\n"
    out += "        visitorProtocols.enumerated().map { ($0, $1.violations) }\n"
    out += "    }\n"

    out += "}\n"

    return out
  }

  /// Convert a SwiftSyntax type name to a property name
  /// e.g. "FunctionDeclSyntax" -> "functionDecl_visit" or "functionDecl_visitPost"
  private static func propertyName(for nodeType: String, kind: String) -> String {
    var name = nodeType
    if name.hasSuffix("Syntax") {
      name = String(name.dropLast(6))
    }
    let first = name.prefix(1).lowercased()
    name = first + name.dropFirst()
    return "\(name)_\(kind)"
  }
}
