import Foundation

/// Generates the RuleRegistry+AllRules.generated.swift file
enum RegistryEmitter {
  static func emit(ruleTypes: [RuleTypeInfo]) -> String {
    let sorted = ruleTypes.sorted { $0.typeName < $1.typeName }

    var lines: [String] = []
    lines.append("// swiftlint:disable:this file_length")
    lines.append("// Generated by GeneratePipeline — do not edit")
    lines.append("")
    lines.append("import SwiftiomaticSyntax")
    lines.append("")
    lines.append("private let _registerAllRulesOnceImpl: Void = {")
    lines.append("  RuleRegistry.shared.register(rules: allRules)")
    lines.append("}()")
    lines.append("")
    lines.append("extension RuleRegistry {")
    lines
      .append(
        "  /// Register all rules, should only be called once before any linting code is executed",
      )
    lines.append("  public static func registerAllRulesOnce() {")
    lines.append("    _ = _registerAllRulesOnceImpl")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("/// All available built-in rules")
    lines.append("private let allRules: [any Rule.Type] = [")
    for ruleType in sorted {
      lines.append("  \(ruleType.typeName).self,")
    }
    lines.append("]")
    lines.append("")

    // Emit category extensions derived from directory structure
    let categorized = sorted.filter { $0.categoryName != nil }
    if categorized.isNotEmpty {
      lines.append("// MARK: - Categories (derived from directory structure)")
      lines.append("")
      for ruleType in categorized {
        guard let cat = ruleType.categoryName else { continue }
        if let sub = ruleType.subcategoryName {
          lines.append(
            "extension \(ruleType.typeName) { static let category = RuleCategory(name: \"\(cat)\", subcategory: \"\(sub)\") }"
          )
        } else {
          lines.append(
            "extension \(ruleType.typeName) { static let category = RuleCategory(name: \"\(cat)\") }"
          )
        }
      }
      lines.append("")
    }

    return lines.joined(separator: "\n")
  }
}

extension Array {
  fileprivate var isNotEmpty: Bool { !isEmpty }
}
