import Foundation

/// Generates `CompactStageOneRewriter+Generated.swift`: a single `SyntaxRewriter` that
/// runs every node-local rewrite rule (those exposing `static func transform(_:context:)`)
/// in one tree walk. Replaces the legacy `RewritePipeline.rewrite` loop, which started a
/// fresh full-tree walk per rule.
///
/// See epic `iv7-r5g` and sub-issue `ogx-lb7` for the architectural premise.
package final class CompactStageOneRewriterGenerator: FileGenerator {

    let collector: RuleCollector

    /// Node types whose dispatch is hand-written as a free function
    /// `rewrite<NodeType>(_:context:)` in `Sources/SwiftiomaticKit/Rewrites/`.
    /// For these, the generator emits a `visit` override that calls the free
    /// function instead of chaining per-rule static transforms.
    ///
    /// Per Phase 4 of `ddi-wtv`, sub-issues progressively migrate node types
    /// from the per-rule chain to the merged free-function form. When all
    /// node-local rules are merged, the per-rule dispatch path goes away.
    private static let manuallyHandledNodeTypes: Set<String> = [
        "SourceFileSyntax",
        "TokenSyntax",
    ]

    package init(collector: RuleCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        var result = ""
        result += """
            //===----------------------------------------------------------------------===//
            //
            // This source file is part of the Swift.org open source project
            //
            // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
            // Licensed under Apache License v2.0 with Runtime Library Exception
            //
            // See https://swift.org/LICENSE.txt for license information
            // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
            //
            //===----------------------------------------------------------------------===//

            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            // sm:ignore-file: fileLength, typeBodyLength, functionBodyLength

            import SwiftSyntax

            /// The combined node-local rewrite stage for the `compact` style. Each `visit(_:)`
            /// override defers to `super.visit` to recurse children, then applies every rule
            /// that opted into `static func transform(_:context:)` for that node type.
            ///
            /// Rules are dispatched in alphabetical order by type name; same-node-type
            /// interactions should be expressed via `MustRunAfter` (future) or by composing
            /// transforms inside a single rule.
            final class CompactStageOneRewriter: SyntaxRewriter {

                let context: Context

                init(context: Context) {
                    self.context = context
                    super.init()
                }

            """

        // Union of every node type that any rule has opted into via
        // `transform`, `willEnter`, or `didExit`. We need an override for each
        // so that scope-only rules (no transform) still get their hooks fired.
        var allNodeTypes = Set(collector.nodeLocalTransforms.keys)
        allNodeTypes.formUnion(collector.nodeLocalWillEnter.keys)
        allNodeTypes.formUnion(collector.nodeLocalDidExit.keys)

        // Include manually handled node types even if no rule registered transforms/hooks for them.
        allNodeTypes.formUnion(Self.manuallyHandledNodeTypes)

        for nodeType in allNodeTypes.sorted() {
            // Manually handled: emit a thin override that fires willEnter hooks
            // before super.visit, calls the hand-written free function for the
            // post-traversal transform, and fires didExit hooks afterward.
            //
            // The merged free function `rewrite<NodeType>(_:context:)` is
            // responsible only for the transform; willEnter/didExit stay in the
            // override so file-level pre-scan state (e.g. PreferSwiftTesting's
            // bailOut flag) is populated BEFORE descendants are visited.
            if Self.manuallyHandledNodeTypes.contains(nodeType) {
                let funcName = "rewrite" + nodeType.replacingOccurrences(of: "Syntax", with: "")
                let willEnterRules = (collector.nodeLocalWillEnter[nodeType] ?? []).sorted()
                let didExitRules = (collector.nodeLocalDidExit[nodeType] ?? []).sorted()
                let returnType = Self.returnType(for: nodeType)

                var willEnterBlock = ""
                for ruleName in willEnterRules {
                    willEnterBlock += """
                            if context.shouldFormat(\(ruleName).self, node: Syntax(node)) {
                              \(ruleName).willEnter(node, context: context)
                            }

                        """
                }
                var didExitBlock = ""
                for ruleName in didExitRules {
                    didExitBlock += """
                            if context.shouldFormat(\(ruleName).self, node: Syntax(node)) {
                              \(ruleName).didExit(node, context: context)
                            }

                        """
                }

                if returnType == nodeType {
                    result += """

                          override func visit(_ node: \(nodeType)) -> \(returnType) {
                        \(willEnterBlock)    let visited = super.visit(node)
                            let result = \(funcName)(visited, context: context)
                        \(didExitBlock)    return result
                          }

                        """
                } else {
                    result += """

                          override func visit(_ node: \(nodeType)) -> \(returnType) {
                        \(willEnterBlock)    let visited = super.visit(node)
                            let result: \(returnType)
                            if let concrete = visited.as(\(nodeType).self) {
                              result = \(returnType)(\(funcName)(concrete, context: context))
                            } else {
                              result = visited
                            }
                        \(didExitBlock)    return result
                          }

                        """
                }
                continue
            }

            let transformRules = collector.nodeLocalTransforms[nodeType] ?? []
            let willEnterRules = (collector.nodeLocalWillEnter[nodeType] ?? []).sorted()
            let didExitRules = (collector.nodeLocalDidExit[nodeType] ?? []).sorted()
            let returnType = Self.returnType(for: nodeType)
            let isErased = returnType != nodeType

            // willEnter calls fire before `super.visit` so scope-tracking rules
            // can push state that descendants observe. They take the *original*
            // node, not the post-recursion one.
            var willEnterBlock = ""
            for ruleName in willEnterRules {
                willEnterBlock += """
                        if context.shouldFormat(\(ruleName).self, node: Syntax(node)) {
                          \(ruleName).willEnter(node, context: context)
                        }

                    """
            }

            // didExit calls fire after the chained transforms so scope-tracking
            // rules can pop state. We pass the *original* node (pre-rewrite) so
            // pop logic remains identity-stable across transforms.
            var didExitBlock = ""
            for ruleName in didExitRules {
                didExitBlock += """
                        if context.shouldFormat(\(ruleName).self, node: Syntax(node)) {
                          \(ruleName).didExit(node, context: context)
                        }

                    """
            }

            if isErased {
                // The override signature returns an erased type (DeclSyntax/ExprSyntax/StmtSyntax),
                // which means a transform may produce a different concrete kind. Each rule still
                // takes the concrete input kind, so we re-cast after every step and stop chaining
                // once the kind changes (later transforms wouldn't apply anyway).
                //
                // Capture `Syntax(node).parent` *before* `super.visit` — the post-recursion node
                // is detached from its parent, so transforms that need ancestor context (issue
                // `3zw-l17` Pattern 1) get the original parent here.
                result += """

                      override func visit(_ node: \(nodeType)) -> \(returnType) {
                        let parent = Syntax(node).parent
                    \(willEnterBlock)    var current: \(returnType) = super.visit(node)

                    """
                for ruleName in transformRules.sorted() {
                    result += """
                            if let concrete = current.as(\(nodeType).self),
                              context.shouldFormat(\(ruleName).self, node: Syntax(concrete))
                            {
                              current = \(ruleName).transform(concrete, parent: parent, context: context)
                            }

                        """
                }
                result += """
                    \(didExitBlock)    return current
                      }

                    """
            } else {
                result += """

                      override func visit(_ node: \(nodeType)) -> \(returnType) {
                        let parent = Syntax(node).parent
                    \(willEnterBlock)    var node = super.visit(node)

                    """
                for ruleName in transformRules.sorted() {
                    result += """
                            if context.shouldFormat(\(ruleName).self, node: Syntax(node)) {
                              node = \(ruleName).transform(node, parent: parent, context: context)
                            }

                        """
                }
                result += """
                    \(didExitBlock)    return node
                      }

                    """
            }
        }

        result += """
            }

            """
        return result
    }

    /// `SyntaxRewriter.visit(_:)` for declaration nodes returns `DeclSyntax`; for
    /// expression nodes, `ExprSyntax`; for statement nodes, `StmtSyntax`. For most
    /// other concrete types it returns the same concrete type. Match the upstream
    /// signatures so the override compiles.
    ///
    /// We keep this conservative: for node types whose return type isn't known to
    /// be the protocol-erased form, we use the concrete type. The legacy
    /// `RewritePipeline` rules already encode the right shape, so any mismatch here
    /// surfaces at build time and can be added as needed.
    private static func returnType(for nodeType: String) -> String {
        if Self.declSyntaxKinds.contains(nodeType) { return "DeclSyntax" }
        if Self.exprSyntaxKinds.contains(nodeType) { return "ExprSyntax" }
        if Self.stmtSyntaxKinds.contains(nodeType) { return "StmtSyntax" }
        if Self.typeSyntaxKinds.contains(nodeType) { return "TypeSyntax" }
        return nodeType
    }

    /// Concrete `*TypeSyntax` kinds whose `SyntaxRewriter.visit` returns `TypeSyntax`.
    private static let typeSyntaxKinds: Set<String> = [
        "ArrayTypeSyntax",
        "AttributedTypeSyntax",
        "ClassRestrictionTypeSyntax",
        "CompositionTypeSyntax",
        "DictionaryTypeSyntax",
        "FunctionTypeSyntax",
        "IdentifierTypeSyntax",
        "ImplicitlyUnwrappedOptionalTypeSyntax",
        "MemberTypeSyntax",
        "MetatypeTypeSyntax",
        "MissingTypeSyntax",
        "NamedOpaqueReturnTypeSyntax",
        "OptionalTypeSyntax",
        "PackElementTypeSyntax",
        "PackExpansionTypeSyntax",
        "SomeOrAnyTypeSyntax",
        "SuppressedTypeSyntax",
        "TupleTypeSyntax",
    ]

    /// Concrete `*DeclSyntax` kinds whose `SyntaxRewriter.visit` returns `DeclSyntax`.
    /// Sourced from the swift-syntax declarations matching the `*DeclSyntax` naming
    /// convention. Add entries here as rules adopt new declaration node types.
    private static let declSyntaxKinds: Set<String> = [
        "AccessorDeclSyntax",
        "ActorDeclSyntax",
        "AssociatedTypeDeclSyntax",
        "ClassDeclSyntax",
        "DeinitializerDeclSyntax",
        "EditorPlaceholderDeclSyntax",
        "EnumCaseDeclSyntax",
        "EnumDeclSyntax",
        "ExtensionDeclSyntax",
        "FunctionDeclSyntax",
        "IfConfigDeclSyntax",
        "ImportDeclSyntax",
        "InitializerDeclSyntax",
        "MacroDeclSyntax",
        "MacroExpansionDeclSyntax",
        "MissingDeclSyntax",
        "OperatorDeclSyntax",
        "PoundSourceLocationSyntax",
        "PrecedenceGroupDeclSyntax",
        "ProtocolDeclSyntax",
        "StructDeclSyntax",
        "SubscriptDeclSyntax",
        "TypeAliasDeclSyntax",
        "VariableDeclSyntax",
    ]

    /// Concrete `*ExprSyntax` kinds whose `SyntaxRewriter.visit` returns `ExprSyntax`.
    /// Add entries as rules adopt new expression node types.
    private static let exprSyntaxKinds: Set<String> = [
        "ArrayExprSyntax",
        "ArrowExprSyntax",
        "AsExprSyntax",
        "AssignmentExprSyntax",
        "AwaitExprSyntax",
        "BinaryOperatorExprSyntax",
        "BooleanLiteralExprSyntax",
        "BorrowExprSyntax",
        "CanImportExprSyntax",
        "CanImportVersionInfoSyntax",
        "ClosureExprSyntax",
        "ConsumeExprSyntax",
        "CopyExprSyntax",
        "DeclReferenceExprSyntax",
        "DictionaryExprSyntax",
        "DiscardAssignmentExprSyntax",
        "DoExprSyntax",
        "EditorPlaceholderExprSyntax",
        "FloatLiteralExprSyntax",
        "ForceUnwrapExprSyntax",
        "FunctionCallExprSyntax",
        "GenericSpecializationExprSyntax",
        "IfExprSyntax",
        "InOutExprSyntax",
        "InfixOperatorExprSyntax",
        "IntegerLiteralExprSyntax",
        "IsExprSyntax",
        "KeyPathExprSyntax",
        "MacroExpansionExprSyntax",
        "MemberAccessExprSyntax",
        "MissingExprSyntax",
        "NilLiteralExprSyntax",
        "OptionalChainingExprSyntax",
        "PackElementExprSyntax",
        "PackExpansionExprSyntax",
        "PatternExprSyntax",
        "PostfixIfConfigExprSyntax",
        "PostfixOperatorExprSyntax",
        "PrefixOperatorExprSyntax",
        "RegexLiteralExprSyntax",
        "SequenceExprSyntax",
        "SimpleStringLiteralExprSyntax",
        "StringLiteralExprSyntax",
        "SubscriptCallExprSyntax",
        "SuperExprSyntax",
        "SwitchExprSyntax",
        "TernaryExprSyntax",
        "TryExprSyntax",
        "TupleExprSyntax",
        "TypeExprSyntax",
        "UnresolvedAsExprSyntax",
        "UnresolvedIsExprSyntax",
        "UnresolvedTernaryExprSyntax",
    ]

    /// Concrete `*StmtSyntax` kinds whose `SyntaxRewriter.visit` returns `StmtSyntax`.
    /// Add entries as rules adopt new statement node types.
    private static let stmtSyntaxKinds: Set<String> = [
        "BreakStmtSyntax",
        "ContinueStmtSyntax",
        "DeferStmtSyntax",
        "DiscardStmtSyntax",
        "DoStmtSyntax",
        "ExpressionStmtSyntax",
        "FallThroughStmtSyntax",
        "ForStmtSyntax",
        "GuardStmtSyntax",
        "LabeledStmtSyntax",
        "MissingStmtSyntax",
        "RepeatStmtSyntax",
        "ReturnStmtSyntax",
        "ThenStmtSyntax",
        "ThrowStmtSyntax",
        "WhileStmtSyntax",
        "YieldStmtSyntax",
    ]
}
