import Foundation

/// Generates `CompactStageOneRewriter+Generated.swift`: a single `SyntaxRewriter` that
/// runs every node-local rewrite rule (those exposing `static func transform(_:context:)`)
/// in one tree walk. Replaces the legacy `RewritePipeline.rewrite` loop, which started a
/// fresh full-tree walk per rule.
///
/// See epic `iv7-r5g` and sub-issue `ogx-lb7` for the architectural premise.
package final class CompactStageOneRewriterGenerator: FileGenerator {

    let collector: RuleCollector

    package init(collector: RuleCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        var result = ""
        result += """
            //===----------------------------------------------------------------------===//
            //
            // This source file is part of the Swift.org open source project
            //
            // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
            // Licensed under Apache License v2.0 with Runtime Library Exception
            //
            // See https://swift.org/LICENSE.txt for license information
            // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
            //
            //===----------------------------------------------------------------------===//

            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            // sm:ignore-file: fileLength, typeBodyLength, functionBodyLength

            import SwiftSyntax

            /// The combined node-local rewrite stage for the `compact` style. Each `visit(_:)`
            /// override defers to `super.visit` to recurse children, then applies every rule
            /// that opted into `static func transform(_:context:)` for that node type.
            ///
            /// Rules are dispatched in alphabetical order by type name; same-node-type
            /// interactions should be expressed via `MustRunAfter` (future) or by composing
            /// transforms inside a single rule.
            final class CompactStageOneRewriter: SyntaxRewriter {

                let context: Context

                init(context: Context) {
                    self.context = context
                    super.init()
                }

            """

        for (nodeType, ruleNames) in collector.nodeLocalTransforms.sorted(by: { $0.key < $1.key }) {
            let returnType = Self.returnType(for: nodeType)
            result += """

                  override func visit(_ node: \(nodeType)) -> \(returnType) {
                    var node = super.visit(node)

                """
            for ruleName in ruleNames.sorted() {
                result += """
                        if context.shouldFormat(\(ruleName).self, node: Syntax(node)) {
                          node = \(ruleName).transform(node, context: context)
                        }

                    """
            }
            result += """
                    return \(Self.wrapForReturn(nodeType: nodeType, returnType: returnType))
                  }

                """
        }

        result += """
            }

            """
        return result
    }

    /// `SyntaxRewriter.visit(_:)` for declaration nodes returns `DeclSyntax`; for
    /// expression nodes, `ExprSyntax`; for statement nodes, `StmtSyntax`. For most
    /// other concrete types it returns the same concrete type. Match the upstream
    /// signatures so the override compiles.
    ///
    /// We keep this conservative: for node types whose return type isn't known to
    /// be the protocol-erased form, we use the concrete type. The legacy
    /// `RewritePipeline` rules already encode the right shape, so any mismatch here
    /// surfaces at build time and can be added as needed.
    private static func returnType(for nodeType: String) -> String {
        if Self.declSyntaxKinds.contains(nodeType) { return "DeclSyntax" }
        if Self.exprSyntaxKinds.contains(nodeType) { return "ExprSyntax" }
        if Self.stmtSyntaxKinds.contains(nodeType) { return "StmtSyntax" }
        return nodeType
    }

    /// When the override returns a protocol-erased type but the node remains the
    /// concrete kind, wrap it in the constructor; otherwise return as-is.
    private static func wrapForReturn(nodeType: String, returnType: String) -> String {
        returnType == nodeType ? "node" : "\(returnType)(node)"
    }

    /// Concrete `*DeclSyntax` kinds whose `SyntaxRewriter.visit` returns `DeclSyntax`.
    /// Sourced from the swift-syntax declarations matching the `*DeclSyntax` naming
    /// convention. Add entries here as rules adopt new declaration node types.
    private static let declSyntaxKinds: Set<String> = [
        "AccessorDeclSyntax",
        "ActorDeclSyntax",
        "AssociatedTypeDeclSyntax",
        "ClassDeclSyntax",
        "DeinitializerDeclSyntax",
        "EditorPlaceholderDeclSyntax",
        "EnumCaseDeclSyntax",
        "EnumDeclSyntax",
        "ExtensionDeclSyntax",
        "FunctionDeclSyntax",
        "IfConfigDeclSyntax",
        "ImportDeclSyntax",
        "InitializerDeclSyntax",
        "MacroDeclSyntax",
        "MacroExpansionDeclSyntax",
        "MissingDeclSyntax",
        "OperatorDeclSyntax",
        "PoundSourceLocationSyntax",
        "PrecedenceGroupDeclSyntax",
        "ProtocolDeclSyntax",
        "StructDeclSyntax",
        "SubscriptDeclSyntax",
        "TypeAliasDeclSyntax",
        "VariableDeclSyntax",
    ]

    /// Concrete `*ExprSyntax` kinds whose `SyntaxRewriter.visit` returns `ExprSyntax`.
    /// Add entries as rules adopt new expression node types.
    private static let exprSyntaxKinds: Set<String> = [
        "ArrayExprSyntax",
        "ArrowExprSyntax",
        "AsExprSyntax",
        "AssignmentExprSyntax",
        "AwaitExprSyntax",
        "BinaryOperatorExprSyntax",
        "BooleanLiteralExprSyntax",
        "BorrowExprSyntax",
        "CanImportExprSyntax",
        "CanImportVersionInfoSyntax",
        "ClosureExprSyntax",
        "ConsumeExprSyntax",
        "CopyExprSyntax",
        "DeclReferenceExprSyntax",
        "DictionaryExprSyntax",
        "DiscardAssignmentExprSyntax",
        "DoExprSyntax",
        "EditorPlaceholderExprSyntax",
        "FloatLiteralExprSyntax",
        "ForceUnwrapExprSyntax",
        "FunctionCallExprSyntax",
        "GenericSpecializationExprSyntax",
        "IfExprSyntax",
        "InOutExprSyntax",
        "InfixOperatorExprSyntax",
        "IntegerLiteralExprSyntax",
        "IsExprSyntax",
        "KeyPathExprSyntax",
        "MacroExpansionExprSyntax",
        "MemberAccessExprSyntax",
        "MissingExprSyntax",
        "NilLiteralExprSyntax",
        "OptionalChainingExprSyntax",
        "PackElementExprSyntax",
        "PackExpansionExprSyntax",
        "PatternExprSyntax",
        "PostfixIfConfigExprSyntax",
        "PostfixOperatorExprSyntax",
        "PrefixOperatorExprSyntax",
        "RegexLiteralExprSyntax",
        "SequenceExprSyntax",
        "SimpleStringLiteralExprSyntax",
        "StringLiteralExprSyntax",
        "SubscriptCallExprSyntax",
        "SuperExprSyntax",
        "SwitchExprSyntax",
        "TernaryExprSyntax",
        "TryExprSyntax",
        "TupleExprSyntax",
        "TypeExprSyntax",
        "UnresolvedAsExprSyntax",
        "UnresolvedIsExprSyntax",
        "UnresolvedTernaryExprSyntax",
    ]

    /// Concrete `*StmtSyntax` kinds whose `SyntaxRewriter.visit` returns `StmtSyntax`.
    /// Add entries as rules adopt new statement node types.
    private static let stmtSyntaxKinds: Set<String> = [
        "BreakStmtSyntax",
        "ContinueStmtSyntax",
        "DeferStmtSyntax",
        "DiscardStmtSyntax",
        "DoStmtSyntax",
        "ExpressionStmtSyntax",
        "FallThroughStmtSyntax",
        "ForStmtSyntax",
        "GuardStmtSyntax",
        "LabeledStmtSyntax",
        "MissingStmtSyntax",
        "RepeatStmtSyntax",
        "ReturnStmtSyntax",
        "ThenStmtSyntax",
        "ThrowStmtSyntax",
        "WhileStmtSyntax",
        "YieldStmtSyntax",
    ]
}
