//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import ConfigurationKit
import Foundation

/// Generates the rule registry file with type arrays for rules and settings.
/// All metadata (names, defaults, groups) is derived at runtime from the types
/// via protocol witness dispatch on the `Rule` existential.
package final class ConfigurationGenerator: FileGenerator {
    let collector: RuleCollector

    package init(collector: RuleCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        let sortedRules = collector.lintingSyntaxRules.sorted(by: { $0.typeName < $1.typeName })
        let sortedSettings = collector.layoutRules.sorted(by: { $0.typeName < $1.typeName })

        var result = fileHeader
        result += "package enum ConfigurationRegistry {\n\n"

        // Setting types
        result += "    /// All known layout setting types.\n"
        result += "    package static let allSettingTypes: [any LayoutRule.Type] = [\n"
        for setting in sortedSettings {
            result += "        \(setting.typeName).self,\n"
        }
        result += "    ]\n\n"

        // Rule types (internal because Rule is internal)
        result += "    /// All known rule types.\n"
        result += "    static let allRuleTypes: [any SyntaxRule.Type] = [\n"
        for rule in sortedRules {
            result += "        \(rule.typeName).self,\n"
        }
        result += "    ]\n"

        result += "}\n"
        return result
    }

    private var fileHeader: String {
        """
        //===----------------------------------------------------------------------===//
        //
        // This source file is part of the Swift.org open source project
        //
        // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
        // Licensed under Apache License v2.0 with Runtime Library Exception
        //
        // See https://swift.org/LICENSE.txt for license information
        // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
        //
        //===----------------------------------------------------------------------===//

        // sm:disable fileLength
        // This file is automatically generated with generate-swiftiomatic. Do not edit!

        """
    }
}
