//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation
import ConfigurationKit

/// Generates the rule registry file with type arrays for rules and settings.
/// All metadata (names, defaults, groups) is derived at runtime from the types
/// via protocol witness dispatch on the `Rule` existential.
package final class ConfigurationGenerator: FileGenerator {
    let collector: ConfigurableCollector

    package init(collector: ConfigurableCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        let sortedRules = collector.allLinters.sorted(by: { $0.typeName < $1.typeName })
        let sortedSettings = collector.allSettings.sorted(by: { $0.typeName < $1.typeName })

        var result = fileHeader
        result += "package enum ConfigurationRegistry {\n\n"

        // Setting types
        result += "    /// All known layout setting types.\n"
        result += "    package static let allSettingTypes: [any LayoutDescriptor.Type] = [\n"
        for setting in sortedSettings {
            result += "        \(setting.typeName).self,\n"
        }
        result += "    ]\n\n"

        // Rule types (internal because Rule is internal)
        result += "    /// All known rule types.\n"
        result += "    static let allRuleTypes: [any SyntaxRule.Type] = [\n"
        for rule in sortedRules {
            result += "        \(rule.typeName).self,\n"
        }
        result += "    ]\n"

        result += "}\n"
        return result
    }

    /// Derives an option name by lowercasing the first character of the type name.
    static func optionName(for typeName: String) -> String {
        guard let first = typeName.first else { return typeName }
        return first.lowercased() + typeName.dropFirst()
    }

    private var fileHeader: String {
        """
        //===----------------------------------------------------------------------===//
        //
        // This source file is part of the Swift.org open source project
        //
        // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
        // Licensed under Apache License v2.0 with Runtime Library Exception
        //
        // See https://swift.org/LICENSE.txt for license information
        // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
        //
        //===----------------------------------------------------------------------===//

        // This file is automatically generated with generate-swiftiomatic. Do not edit!

        """
    }
}
