//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2023 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// Generates the markdown file with extended documentation on the available rules.
package final class DocumentationGenerator: FileGenerator {
  /// The rules collected by scanning the formatter source code.
  let collector: RuleCollector

  /// Creates a new rule registry generator.
  package init(collector: RuleCollector) {
    self.collector = collector
  }

  package func generateContent() -> String {
    var result = ""
    result += """
      <!-- This file is automatically generated with generate-swiftiomatic. Do not edit! -->

      # `sm` Lint and Format Rules

      Use the rules below in the `rules` block of your `swiftiomatic.json`
      configuration file, as described in
      [Configuration](Documentation/Configuration.md). All of these rules can be
      applied in the linter, but only some of them can format your source code
      automatically.

      Here's the list of available rules:


      """
    for detectedRule in collector.lintingSyntaxRules.sorted(by: { $0.configKey < $1.configKey }) {
      result += "- [\(detectedRule.configKey)](#\(detectedRule.configKey))\n"
    }
    for detectedRule in collector.lintingSyntaxRules.sorted(by: { $0.configKey < $1.configKey }) {
      result += """

        ### \(detectedRule.configKey)

        \(detectedRule.description ?? "")
        \(ruleFormatSupportDescription(for: detectedRule))

        """
    }
    return result
  }

  private func ruleFormatSupportDescription(for rule: RuleCollector.DetectedSyntaxRule) -> String {
    return rule.canRewrite
      ? "`\(rule.configKey)` rule can format your code automatically." : "`\(rule.configKey)` is a linter-only rule."
  }
}
