//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// Paths for files generated by the `generate-swiftiomatic` tool.
///
/// Create with a package root URL. For the standalone executable,
/// use the ``filePath`` convenience that derives the root from `#filePath`.
package struct GeneratePaths {

    // MARK: - Convenience for standalone executable

    /// Paths derived from this source file's location (`Sources/GeneratorKit/`).
    package static let filePath = GeneratePaths(
        packageRoot: URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // GeneratorKit/
            .deletingLastPathComponent()  // Sources/
            .deletingLastPathComponent()  // package root
    )

    // MARK: - Instance properties

    /// The package root directory.
    package let packageRoot: URL

    /// The directory containing rule implementations to scan.
    package let syntaxRulesFolder: URL

    /// The directory containing layout setting descriptors to scan.
    package let layoutRulesFolder: URL

    /// The directory containing `TokenStream+*.swift` token stream extension files.
    package let tokenFolder: URL

    /// The generated pipelines file (`LintPipeline` + `FormatPipeline` extensions).
    package let pipelineFile: URL

    /// The generated rule registry file (type arrays, default enablements, name cache).
    package let ruleRegistryFile: URL

    /// The generated rule documentation markdown file.
    package let ruleDocumentationFile: URL

    /// The generated JSON Schema for configuration files.
    package let configurationSchemaFile: URL

    /// The generated `TokenStream` subclass with forwarding stubs.
    package let tokenStreamStubsFile: URL

    /// The generated Swift file embedding the JSON Schema as a string literal.
    package let configurationSchemaSwiftFile: URL

    // MARK: - Initializers

    /// Creates paths rooted at the given package directory.
    ///
    /// Output files go to `Sources/SwiftiomaticKit/Generated/`.
    package init(packageRoot: URL) {
        let generated =
            packageRoot
            .appending(path: "Sources")
            .appending(path: "SwiftiomaticKit")
            .appending(path: "Generated")
        self.init(packageRoot: packageRoot, outputDirectory: generated)
    }

    /// Creates paths with input directories derived from `packageRoot`
    /// and output files directed to `outputDirectory`.
    ///
    /// Used by the build tool plugin to write generated files into the
    /// plugin work directory instead of the source tree.
    package init(packageRoot: URL, outputDirectory: URL) {
        self.packageRoot = packageRoot

        let sources = packageRoot.appending(path: "Sources")
        let kit = sources.appending(path: "SwiftiomaticKit")
        let layout = kit.appending(path: "Layout")
        let syntax = kit.appending(path: "Syntax")

        tokenFolder = layout.appending(path: "Tokens")
        layoutRulesFolder = layout.appending(path: "Rules")
        syntaxRulesFolder = syntax.appending(path: "Rules")

        pipelineFile = outputDirectory.appending(path: "Pipelines+Generated.swift")
        ruleRegistryFile = outputDirectory.appending(path: "ConfigurationRegistry+Generated.swift")
        ruleDocumentationFile = packageRoot.appending(path: "Documentation")
            .appending(path: "RuleDocumentation.md")
        configurationSchemaFile = packageRoot.appending(path: "schema.json")
        tokenStreamStubsFile = outputDirectory.appending(path: "TokenStream+Generated.swift")
        configurationSchemaSwiftFile = outputDirectory.appending(
            path: "ConfigurationSchema+Generated.swift")
    }
}
