//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// Paths for files generated by the `generate-swiftiomatic` tool.
///
/// All paths are derived from the location of this source file (`#filePath`),
/// walking up to `Sources/` and then into the appropriate target directories.
package enum GenerateSwiftiomaticPaths {

    // MARK: - Directory & file name constants

    /// The target directory containing the main SwiftiomaticKit library sources.
    private static let kitTarget = "SwiftiomaticKit"

    /// The subdirectory within the kit target that contains rule implementations.
    private static let rulesSubdirectory = "Rules"

    /// The subdirectory within the kit target for core infrastructure files.
    private static let coreSubdirectory = "Core"

    /// The documentation directory at the package root.
    private static let documentationDirectory = "Documentation"

    // MARK: - Generated file names

    private static let pipelinesFileName = "Pipelines+Generated.swift"
    private static let ruleRegistryFileName = "RuleRegistry+Generated.swift"
    private static let ruleNameCacheFileName = "RuleNameCache+Generated.swift"
    private static let ruleDocumentationFileName = "RuleDocumentation.md"
    private static let configurationSchemaFileName = "schema.json"

    // MARK: - Derived paths

    /// The `Sources/` directory, derived from this file's location in `Sources/GeneratorKit/`.
    private static let sourcesDirectory =
        URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()

    /// The package root directory (parent of `Sources/`).
    private static let packageRoot =
        sourcesDirectory.deletingLastPathComponent()

    /// The directory containing rule implementations to scan.
    package static let rulesDirectory =
        sourcesDirectory
        .appendingPathComponent(kitTarget)
        .appendingPathComponent(rulesSubdirectory)

    /// The generated pipelines file (`LintPipeline` + `FormatPipeline` extensions).
    package static let pipelineFile =
        sourcesDirectory
        .appendingPathComponent(kitTarget)
        .appendingPathComponent(coreSubdirectory)
        .appendingPathComponent(pipelinesFileName)

    /// The generated rule registry file (default rule enablements).
    package static let ruleRegistryFile =
        sourcesDirectory
        .appendingPathComponent(kitTarget)
        .appendingPathComponent(coreSubdirectory)
        .appendingPathComponent(ruleRegistryFileName)

    /// The generated rule name cache file (`ObjectIdentifier` → rule name mapping).
    package static let ruleNameCacheFile =
        sourcesDirectory
        .appendingPathComponent(kitTarget)
        .appendingPathComponent(coreSubdirectory)
        .appendingPathComponent(ruleNameCacheFileName)

    /// The generated rule documentation markdown file.
    package static let ruleDocumentationFile =
        packageRoot
        .appendingPathComponent(documentationDirectory)
        .appendingPathComponent(ruleDocumentationFileName)

    /// The generated JSON Schema for configuration files.
    package static let configurationSchemaFile =
        packageRoot
        .appendingPathComponent(configurationSchemaFileName)
}
