import Foundation

/// Generates `PassManifest.md` — a reviewable record of which rule lives in which
/// multi-pass `RewritePipeline` pass, and why.
///
/// The manifest is the human-facing audit trail for the migration tracked in issue
/// `qm5-qyp`. Reviewers read it to understand: what changed in this PR (rules moving
/// between passes), which rules are still in the catch-all, and which classifications
/// have load-bearing markers (`Idempotent`, `MonotonicWrite`, ordering hatches).
package final class PassManifestGenerator: FileGenerator {
    let collector: RuleCollector

    package init(collector: RuleCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        let detected = collector.rewritingSyntaxRules.map {
            (typeName: $0.typeName, classification: $0.passClassification)
        }
        let passes = PassPartitioner.partition(rules: detected)
        let classifiedCount = detected.filter { $0.classification?.isUnclassified == false }.count

        var lines: [String] = []
        lines.append("<!-- Generated by `swift run Generator`. Do not edit by hand. -->")
        lines.append("")
        lines.append("# Pass Manifest")
        lines.append("")
        lines.append(
            "Tracks the partition the multi-pass `RewritePipeline` will run, derived from each rule's "
                + "conformance to the markers in "
                + "`Sources/SwiftiomaticKit/PassClassification/PassClassification.swift`."
        )
        lines.append("")
        lines.append(
            "Generated by `Generator` after `RuleCollector` scans `Sources/SwiftiomaticKit/Rules/`. "
                + "See issue `qm5-qyp` for the design and `ain-794` for the codegen that produces this file."
        )
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append("- Rules total: \(detected.count)")
        lines.append("- Rules classified: \(classifiedCount)")
        lines.append("- Rules still in catch-all: \(detected.count - classifiedCount)")
        lines.append("- Passes: \(passes.count)")
        lines.append("")

        for pass in passes {
            lines.append("## Pass `\(pass.name)` — \(pass.label)")
            lines.append("")
            lines.append("Execution: `\(passKindDescription(pass.kind))`")
            lines.append("")
            if pass.ruleTypeNames.isEmpty {
                lines.append("_(no rules)_")
            } else {
                for ruleName in pass.ruleTypeNames {
                    let classification = detected.first(where: { $0.typeName == ruleName })?
                        .classification
                    lines.append("- `\(ruleName)` — \(describe(classification))")
                }
            }
            lines.append("")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private func passKindDescription(_ kind: GeneratedPass.Kind) -> String {
        switch kind {
            case .soloPerRule: "solo per rule (one full-tree walk per rule)"
            case .combined: "combined (single interleaved walk)"
        }
    }

    private func describe(_ classification: PassClassification?) -> String {
        guard let classification, !classification.isUnclassified else { return "unclassified" }
        var pieces: [String] = []
        if let read = classification.readLocality { pieces.append(read) }
        if let write = classification.writeSurface { pieces.append(write) }
        pieces.append(contentsOf: classification.markers)
        return pieces.joined(separator: " + ")
    }
}
