//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// Generates the extensions to the lint and format pipelines.
package final class PipelineGenerator: FileGenerator {

    /// The rules collected by scanning the formatter source code.
    let collector: RuleCollector

    /// Creates a new pipeline generator.
    package init(collector: RuleCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        var result = ""
        result += """
            //===----------------------------------------------------------------------===//
            //
            // This source file is part of the Swift.org open source project
            //
            // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
            // Licensed under Apache License v2.0 with Runtime Library Exception
            //
            // See https://swift.org/LICENSE.txt for license information
            // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
            //
            //===----------------------------------------------------------------------===//

            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            import SwiftSyntax

            /// A syntax visitor that delegates to individual rules for linting.
            ///
            /// This file will be extended with `visit` methods in Pipelines+Generated.swift.
            class LintPipeline: SyntaxVisitor {

              /// The formatter context.
              let context: Context

              /// Stores lint and format rule instances, indexed by the `ObjectIdentifier` of a rule's
              /// class type.
              var ruleCache = [ObjectIdentifier: any SyntaxRule]()

              /// Rules present in this dictionary skip visiting children until they leave the
              /// syntax node stored as their value
              var shouldSkipChildren = [ObjectIdentifier: SyntaxProtocol]()

              /// Creates a new lint pipeline.
              init(context: Context) {
                self.context = context
                super.init(viewMode: .sourceAccurate)
              }

            """

        for (nodeType, lintRules) in collector.syntaxNodeLinters.sorted(by: { $0.key < $1.key }) {
            result += """

                  override func visit(_ node: \(nodeType)) -> SyntaxVisitorContinueKind {

                """
            for ruleName in lintRules.sorted() {
                result += """
                        visitIfEnabled(\(ruleName).visit, for: node)

                    """
            }
            result += """
                    return .visitChildren
                  }

                """
            result += """
                  override func visitPost(_ node: \(nodeType)) {

                """
            for ruleName in lintRules.sorted() {
                result += """
                        onVisitPost(rule: \(ruleName).self, for: node)

                    """
            }
            result += """
                  }

                """
        }

        result += """
            }

            extension RewritePipeline {

              func rewrite(_ node: Syntax) -> Syntax {
                var node = node

            """
        for ruleName in collector.rewritingSyntaxRules.map({ $0.typeName }).sorted() {
            result += """
                    if context.shouldFormat(\(ruleName).self, node: node) {
                      node = \(ruleName)(context: context).rewrite(node)
                    }

                """
        }
        result += """
                return node
              }
            }

            extension MultiPassRewritePipeline {

              func rewrite(_ node: Syntax) -> Syntax {
                var node = node

            """

        let detected = collector.rewritingSyntaxRules.map {
            (typeName: $0.typeName, classification: $0.passClassification)
        }
        let passes = PassPartitioner.partition(rules: detected)
        for pass in passes {
            result += "        // Pass: \(pass.label)\n"
            switch pass.kind {
                case .soloPerRule:
                    for ruleName in pass.ruleTypeNames {
                        result += """
                                if context.shouldFormat(\(ruleName).self, node: node) {
                                  node = \(ruleName)(context: context).rewrite(node)
                                }

                            """
                    }
                case .combined:
                    // Combined-rewriter codegen lands with `7x2-5eg` (token-only
                    // migration). Today every classified rule still falls into the
                    // catch-all so this branch is unreachable.
                    result += "        // (combined codegen pending)\n"
            }
        }

        result += """
                return node
              }
            }

            """
        return result
    }
}
