//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// Generates the extensions to the lint and format pipelines.
package final class PipelineGenerator: FileGenerator {
    /// The rules collected by scanning the formatter source code.
    let collector: RuleCollector

    /// Creates a new pipeline generator.
    package init(collector: RuleCollector) { self.collector = collector }

    package func generateContent() -> String {
        var result = ""
        result += """
            //===----------------------------------------------------------------------===//
            //
            // This source file is part of the Swift.org open source project
            //
            // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
            // Licensed under Apache License v2.0 with Runtime Library Exception
            //
            // See https://swift.org/LICENSE.txt for license information
            // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
            //
            //===----------------------------------------------------------------------===//

            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            // sm:ignore

            import SwiftSyntax

            /// A syntax visitor that delegates to individual rules for linting.
            ///
            /// This file will be extended with `visit` methods in Pipelines+Generated.swift.
            class LintPipeline: SyntaxVisitor {

              /// The formatter context.
              let context: Context

              /// Stores lint and format rule instances, indexed by the `ObjectIdentifier` of a rule's
              /// class type.
              var ruleCache = [ObjectIdentifier: any SyntaxRule]()

              /// Rules present in this dictionary skip visiting children until they leave the
              /// syntax node stored as their value
              var shouldSkipChildren = [ObjectIdentifier: SyntaxProtocol]()

              /// Creates a new lint pipeline.
              init(context: Context) {
                self.context = context
                super.init(viewMode: .sourceAccurate)
              }

            """

        let rewriterNames = Set(collector.rewritingSyntaxRules.map(\.typeName))

        for (nodeType, lintRules) in collector.syntaxNodeLinters.sorted(by: { $0.key < $1.key }) {
            // A file-wide rule gates at the end of the file, and a gate caches the start location,
            // so SourceFileSyntax keeps the node-taking overload.
            let usesGate = nodeType != "SourceFileSyntax"
            let sortedRules = lintRules.sorted()
            result += """

                  override func visit(_ node: \(nodeType)) -> SyntaxVisitorContinueKind {

                """

            if usesGate {
                result += """
                        guard let gate = context.gate(for: node) else { return .visitChildren }

                    """
            }

            for ruleName in sortedRules {
                result += """
                        visitIfEnabled(\(ruleName).visit, for: node\(usesGate ? ", gate: gate" : ""))

                    """
            }
            result += """
                    return .visitChildren
                  }

                """
            result += """
                  override func visitPost(_ node: \(nodeType)) {

                """

            for ruleName in sortedRules {
                if rewriterNames.contains(ruleName) {
                    result += """
                            onVisitPost(rule: \(ruleName).self, for: node)

                        """
                } else {
                    result += """
                            onVisitPost(\(ruleName).visitPost, for: node)

                        """
                }
            }
            result += """
                  }

                """
        }

        result += """
            }

            """
        return result
    }
}
