import Foundation

/// Generates `RewritePipeline` , the single tree walk that dispatches every node-local format rule.
///
/// Each `visit` override is derived from the hooks the rules declare, so a rule reaches every node
/// kind it has an overload for. The hand-written version required registering a rule once per
/// override, and a rule left out of one override failed silently.
package final class RewritePipelineGenerator: FileGenerator {
    let collector: RewriteHookCollector

    package init(collector: RewriteHookCollector) { self.collector = collector }

    /// Node kinds whose `SyntaxRewriter.visit` returns the concrete type even though the name ends
    /// in a base-type suffix. `LabeledExprSyntax` is a tuple or argument element, not an
    /// expression.
    private static let concreteResultExceptions: Set<String> = ["LabeledExprSyntax"]

    /// The column the generated file has to fit, which decides every wrap below.
    private static let columnLimit = 100

    /// Node kinds whose transform chain lives in a hand-written function, mapped to that function.
    ///
    /// `rewriteSourceFile` runs the file-level transforms once over the settled tree, so it takes
    /// the result of `super.visit` rather than a chain of `apply` calls.
    private static let externalTails = ["SourceFileSyntax": "rewriteSourceFile"]

    /// The type `SyntaxRewriter.visit(_:)` returns for a node kind.
    ///
    /// swift-syntax names a node after the base protocol it satisfies, so the suffix decides the
    /// signature. A wrong answer here is a compile error in the generated file, never a silent
    /// behaviour change.
    static func resultType(for node: String) -> String {
        if concreteResultExceptions.contains(node) { return node }
        for base in ["DeclSyntax", "ExprSyntax", "StmtSyntax", "PatternSyntax", "TypeSyntax"]
            where node.hasSuffix(base) && node != base
        { return base }
        return node
    }

    package func generateContent() -> String {
        var result = """
            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            // sm:ignore

            import SwiftSyntax

            /// The combined node-local rewrite stage that dispatches every format rule in a single
            /// tree walk.
            ///
            /// Each `visit(_:)` override defers to `super.visit` to recurse into the children, then
            /// applies every rule that declares a `transform` for that node type, in `rewriteOrder`
            /// . Scope hooks (`willEnter` / `didExit`) bracket the recursion.
            ///
            /// The apply helpers live in `RewritePipeline.swift` .
            final class RewritePipeline: SyntaxRewriter {
                let context: Context

                init(context: Context) {
                    self.context = context
                    super.init()
                }


            """

        // `TokenSyntax` is skipped here because its override is emitted verbatim below. Emitting it
        // twice would not compile, and `RewriteDispatchAudit` already proves `rewriteToken` names
        // every token rule.
        for node in collector.hooksByNode.keys.sorted() where node != "TokenSyntax" {
            result += render(node: node, hooks: collector.hooksByNode[node] ?? [])
        }
        result += """
                // Token-level rules run inside `rewriteToken` , which owns their order because they
                // also run from the layout writer.
                override func visit(_ node: TokenSyntax) -> TokenSyntax {
                    let parent = Syntax(node).parent
                    let visited = super.visit(node)
                    return rewriteToken(visited, parent: parent, context: context)
                }
            }

            """
        return result
    }

    /// Emits `single` when it fits the column limit, and `wrapped` when it does not.
    ///
    /// A long rule name is the only thing that pushes these lines over, so the wrapped form is
    /// always the same shape with the tail moved down a line.
    private func fitted(_ single: String, else wrapped: String) -> String {
        let longest = single.split(separator: "\n").map(\.count).max() ?? 0
        return longest <= Self.columnLimit ? single : wrapped
    }

    /// Lays the `applyNarrowing` arguments over as few lines as the column limit allows.
    ///
    /// A long rule name and a long node kind can both appear in one call, so one wrapped form is
    /// not enough. Each tier moves one more argument down a line.
    private static func narrowingArguments(rule: String, node: String) -> String {
        let indent = String(repeating: " ", count: 12)
        let all = "\(rule).self, to: &result, as: \(node).self, original: node, gate: gate"
        if indent.count + all.count <= columnLimit { return indent + all + "\n" }

        let head = "\(rule).self, to: &result, as: \(node).self,"
        return indent.count + head.count <= columnLimit
            ? indent + head + "\n" + indent + "original: node, gate: gate\n"
            : indent + "\(rule).self, to: &result,\n"
                + indent + "as: \(node).self, original: node, gate: gate\n"
    }

    // MARK: - One override

    private func render(node: String, hooks: [RewriteHookCollector.Hook]) -> String {
        let resultType = Self.resultType(for: node)
        let tail = Self.externalTails[node]
        // A node kind with a tail hands its whole transform chain to that function, so the override
        // emits the scope hooks and the call.
        let transforms = tail == nil ? hooks.filter(\.hasTransform) : []
        let scoped = hooks.filter { $0.hasWillEnter || $0.hasDidExit }
        var body = ""

        body += "    override func visit(_ node: \(node)) -> \(resultType) {\n"
        body += "        guard let gate = context.gate(for: node)"
            + " else { return super.visit(node) }\n"
        if !transforms.isEmpty || tail != nil {
            body += "        let parent = Syntax(node).parent\n"
        }

        // A rule with both hooks caches its gate decision, so `didExit` cannot run without the
        // matching `willEnter` if the configuration is read twice.
        for hook in scoped where hook.hasDidExit {
            body += fitted(
                "        let run\(hook.rule) = "
                    + "context.shouldRewrite(\(hook.rule).self, gate: gate)\n",
                else: "        let run\(hook.rule) = context.shouldRewrite(\n"
                    + "            \(hook.rule).self, gate: gate)\n"
            )
        }
        for hook in scoped where hook.hasWillEnter {
            body += hook.hasDidExit
                ? fitted(
                    "        if run\(hook.rule) "
                        + "{ \(hook.rule).willEnter(node, context: context) }\n",
                    else: "        if run\(hook.rule) {\n"
                        + "            \(hook.rule).willEnter(node, context: context)\n"
                        + "        }\n"
                )
                : """
                        if context.shouldRewrite(\(hook.rule).self, gate: gate) {
                            \(hook.rule).willEnter(node, context: context)
                        }

                """
        }
        let exiting = scoped.filter(\.hasDidExit)

        if !exiting.isEmpty {
            body += "\n        defer {\n"

            for hook in exiting {
                body += fitted(
                    "            if run\(hook.rule) "
                        + "{ \(hook.rule).didExit(node, context: context) }\n",
                    else: "            if run\(hook.rule) {\n"
                        + "                \(hook.rule).didExit(node, context: context)\n"
                        + "            }\n"
                )
            }
            body += "        }\n"
        }

        if let tail {
            body += "        let visited = super.visit(node)\n"
            body += "        return \(tail)(visited, parent: parent, context: context)\n    }\n\n"
            return body
        }

        guard !transforms.isEmpty else {
            body += "        return super.visit(node)\n    }\n\n"
            return body
        }

        // A node whose override returns a base type keeps a base-typed accumulator, because a rule
        // is allowed to replace the node with another kind. Every later rule then re-narrows, and a
        // rule whose kind is gone skips itself.
        body += resultType == node
            ? "        var result = super.visit(node)\n"
            : "        var result: \(resultType) = super.visit(node)\n"

        for hook in transforms {
            body += resultType == node
                ? fitted(
                    """
                            apply(\(hook.rule).self, to: &result, original: node, gate: gate) {
                                \(hook.rule).transform($0, original: $1, parent: parent, context: $2)
                            }

                    """,
                    else: """
                                apply(
                                    \(hook.rule).self, to: &result, original: node, gate: gate
                                ) {
                                    \(hook.rule).transform(
                                        $0, original: $1, parent: parent, context: $2)
                                }

                        """)
                : "        applyNarrowing(\n"
                    + Self.narrowingArguments(rule: hook.rule, node: node)
                    + "        ) {\n"
                    + fitted(
                        "            \(hook.rule)"
                            + ".transform($0, original: $1, parent: parent, context: $2)\n",
                        else: "            \(hook.rule).transform(\n"
                            + "                $0, original: $1, parent: parent, context: $2)\n"
                    )
                    + "        }\n\n"
        }
        body += "        return result\n    }\n\n"
        return body
    }
}
