//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation
import ConfigurationKit

/// Generates the rule registry file used to populate the default configuration.
package final class RuleRegistryGenerator: FileGenerator {

    /// The rules collected by scanning the formatter source code.
    let ruleCollector: RuleCollector

    /// Creates a new rule registry generator.
    package init(ruleCollector: RuleCollector) {
        self.ruleCollector = ruleCollector
    }

    package func generateContent() -> String {
        let sorted = ruleCollector.allLinters.sorted(by: { $0.typeName < $1.typeName })

        var result = """
            //===----------------------------------------------------------------------===//
            //
            // This source file is part of the Swift.org open source project
            //
            // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
            // Licensed under Apache License v2.0 with Runtime Library Exception
            //
            // See https://swift.org/LICENSE.txt for license information
            // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
            //
            //===----------------------------------------------------------------------===//

            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            package enum RuleRegistry {
              package static let rules: [String: RuleHandling] = [

            """
        for rule in sorted {
            result += "    \"\(rule.ruleName)\": .\(rule.defaultHandling),\n"
        }
        result += "  ]\n\n"

        // Generate groupRules: [ConfigGroup: [(option, rule)]]
        var groupedRules: [ConfigGroup: [(option: String, rule: String)]] = [:]
        for rule in sorted {
            guard let group = rule.group else { continue }
            let option = Self.optionName(for: rule.ruleName)
            groupedRules[group, default: []].append((option, rule.ruleName))
        }

        if groupedRules.isEmpty {
            result +=
                "  package static let groupRules: [ConfigGroup: [(option: String, rule: String)]] = [:]\n"
        } else {
            result +=
                "  package static let groupRules: [ConfigGroup: [(option: String, rule: String)]] = [\n"
            for group in ConfigGroup.allCases {
                guard let rules = groupedRules[group], !rules.isEmpty else { continue }
                result += "    .\(group): [\n"
                for (option, rule) in rules {
                    result += "      (\"\(option)\", \"\(rule)\"),\n"
                }
                result += "    ],\n"
            }
            result += "  ]\n"
        }

        // Generate groupManagedRules: Set<String>
        result += "\n  package static let groupManagedRules: Set<String> = {\n"
        result += "    var names = Set<String>()\n"
        result += "    for (_, mappings) in groupRules {\n"
        result += "      for (_, rule) in mappings { names.insert(rule) }\n"
        result += "    }\n"
        result += "    return names\n"
        result += "  }()\n"

        result += "}\n"
        return result
    }

    /// Derives an option name by lowercasing the first character of the type name.
    static func optionName(for typeName: String) -> String {
        guard let first = typeName.first else { return typeName }
        return first.lowercased() + typeName.dropFirst()
    }
}
