import Foundation

/// Generates `TokenStream+Generated.swift`, a final subclass of
/// `TokenStreamBase` containing only the `override func visit/visitPost`
/// forwarding stubs discovered by `TokenStreamStubCollector`.
package final class TokenStreamStubGenerator: FileGenerator {
    let collector: SyntaxVisitorOverrideCollector

    package init(collector: SyntaxVisitorOverrideCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        var result = """
            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            import SwiftSyntax

            /// Thin subclass that provides `override func visit/visitPost` stubs forwarding
            /// to the implementation methods in the `TokenStream+*.swift` extension files.
            ///
            /// Swift does not allow overriding methods in extensions of non-@objc classes,
            /// so this generated class exists solely to bridge that gap.
            final class TokenStream: TokenStreamBase {

            """

        for stub in collector.overrides {
            if stub.isPost {
                result += "    override func visitPost(_ \(stub.paramLabel): \(stub.paramType))"
                result += " { \(stub.methodName)(\(stub.paramLabel)) }\n"
            } else {
                result += "    override func visit(_ \(stub.paramLabel): \(stub.paramType))"
                result += " -> SyntaxVisitorContinueKind"
                result += " { \(stub.methodName)(\(stub.paramLabel)) }\n"
            }
        }

        result += "}\n"
        return result
    }
}
