//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// Generates `TokenStream+Generated.swift`, a final subclass of
/// `TokenStreamBase` containing only the `override func visit/visitPost`
/// forwarding stubs discovered by `TokenStreamStubCollector`.
package final class TokenStreamStubGenerator: FileGenerator {

    let collector: TokenStreamStubCollector

    package init(collector: TokenStreamStubCollector) {
        self.collector = collector
    }

    package func generateContent() -> String {
        var result = """
            //===----------------------------------------------------------------------===//
            //
            // This source file is part of the Swift.org open source project
            //
            // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
            // Licensed under Apache License v2.0 with Runtime Library Exception
            //
            // See https://swift.org/LICENSE.txt for license information
            // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
            //
            //===----------------------------------------------------------------------===//

            // This file is automatically generated with generate-swiftiomatic. Do not edit!

            import SwiftSyntax

            /// Thin subclass that provides `override func visit/visitPost` stubs forwarding
            /// to the implementation methods in the `TokenStream+*.swift` extension files.
            ///
            /// Swift does not allow overriding methods in extensions of non-@objc classes,
            /// so this generated class exists solely to bridge that gap.
            final class TokenStream: TokenStreamBase {

            """

        for stub in collector.stubs {
            if stub.isPost {
                result += "    override func visitPost(_ \(stub.paramLabel): \(stub.paramType))"
                result += " { \(stub.methodName)(\(stub.paramLabel)) }\n"
            } else {
                result += "    override func visit(_ \(stub.paramLabel): \(stub.paramType))"
                result += " -> SyntaxVisitorContinueKind"
                result += " { \(stub.methodName)(\(stub.paramLabel)) }\n"
            }
        }

        result += "}\n"
        return result
    }
}
