#!/usr/bin/env bash
# Scan macOS + iOS SDK swiftinterfaces for NotificationCenter.MainActorMessage adapters
# and emit a Swift literal `[notificationName: messageType]` for use by the
# `UseTypedSystemNotification` lint rule.
#
# Run on every Xcode SDK bump; commit the regenerated file.
#
# Output:
#   Sources/SwiftiomaticKit/Rules/Swiftui/NotificationAdapters+Generated.swift
#
# Mapping convention: each `extension <Module>.<Type> { public struct <Foo>Message : ...MainActorMessage }`
# produces an entry keyed by `<Type>.<foo>Notification` (lowercase first letter — the
# Apple-canonical static name) and valued by `<Type>.<Foo>Message`. This covers UIKit/AppKit
# member-form names; Foundation free-floating names (e.g. `NSUndoManagerDidCloseUndoGroup`)
# don't appear in swiftinterfaces and must be supplied by the hand-curated supplement in
# `NotificationAPI.foundationLegacyAdapters`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/Sources/SwiftiomaticKit/Rules/Swiftui/NotificationAdapters+Generated.swift"

# Collect swiftinterfaces from both macOS and iOS SDKs (one arch each — they're identical
# for our purposes). Limit to frameworks that historically host NotificationCenter adapters
# to keep the scan fast.
SDKS=()
for SDK_NAME in macosx iphoneos; do
    if SDK_PATH=$(xcrun --sdk "$SDK_NAME" --show-sdk-path 2>/dev/null); then
        SDKS+=("$SDK_PATH")
    fi
done

if [[ ${#SDKS[@]} -eq 0 ]]; then
    echo "error: no SDKs found via xcrun" >&2
    exit 1
fi

# Per-SDK arch picks: macosx → arm64e-apple-macos, iphoneos → arm64e-apple-ios.
arch_for_sdk() {
    case "$1" in
        */MacOSX*.sdk) echo "arm64e-apple-macos" ;;
        */iPhoneOS*.sdk) echo "arm64e-apple-ios" ;;
        *) echo "" ;;
    esac
}

# Awk script: walks a swiftinterface, tracking the current `extension <Module>.<Type> {`
# scope, and emits one line per nested `public struct <Foo>Message : ...MainActorMessage`.
# Output format: "<Type>\t<Foo>Message"
# shellcheck disable=SC2016  # $1/$2/NF inside awk are field refs, not shell expansions
AWK_EXTRACT='
/^extension [A-Za-z_][A-Za-z0-9_.]+ \{/ {
    # extension Foundation.UndoManager {
    qualified = $2
    n = split(qualified, parts, ".")
    type = parts[n]
    in_ext = 1
    next
}
/^\}/ {
    if (in_ext) { type = ""; in_ext = 0 }
    next
}
in_ext && /public struct [A-Za-z_][A-Za-z0-9_]*Message[[:space:]]*:[^{]*MainActorMessage/ {
    # public struct DidCloseUndoGroupMessage : Foundation.NotificationCenter.MainActorMessage, ...
    for (i = 1; i <= NF; i++) {
        if ($i == "struct") {
            msg = $(i+1)
            sub(/:.*/, "", msg)
            print type "\t" msg
            break
        }
    }
}
'

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

for SDK_PATH in "${SDKS[@]}"; do
    ARCH=$(arch_for_sdk "$SDK_PATH")
    [[ -z "$ARCH" ]] && continue
    while IFS= read -r -d '' iface; do
        awk "$AWK_EXTRACT" "$iface" >> "$TMP" || true
    done < <(find "$SDK_PATH/System/Library/Frameworks" \
                  -name "${ARCH}.swiftinterface" \
                  -path '*/Modules/*.swiftmodule/*' -print0 2>/dev/null)
done

# Deduplicate, sort, build Swift map. Key = "<Type>.<lowerFirst(Foo)>Notification".
ENTRIES=$(sort -u "$TMP" | awk -F'\t' '
{
    type = $1
    msg = $2
    base = msg
    sub(/Message$/, "", base)
    # lowercase first letter of base, append "Notification"
    name = tolower(substr(base, 1, 1)) substr(base, 2) "Notification"
    printf "        \"%s.%s\": \"%s.%s\",\n", type, name, type, msg
}')

cat > "$OUT" <<EOF
// Generated by Scripts/generate-notification-adapters.sh — do not edit by hand.
// Regenerate after Xcode SDK bumps to refresh the system-notification adapter table.

extension NotificationAPI {
    /// Apple-canonical \`<Type>.<member>Notification\` keys whose typed
    /// \`NotificationCenter.MainActorMessage\` adapter was discovered in the current SDK
    /// swiftinterfaces (macOS + iOS).
    static let generatedSystemAdapters: [String: String] = [
$ENTRIES    ]
}
EOF

echo "wrote $OUT ($(grep -c ':' "$OUT") entries)"
