//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation
import SwiftiomaticCore

/// Generates the rule registry file used to populate the default configuration.
@_spi(Internal) public final class RuleRegistryGenerator: FileGenerator {

  /// The rules collected by scanning the formatter source code.
  let ruleCollector: RuleCollector

  /// Creates a new rule registry generator.
  public init(ruleCollector: RuleCollector) {
    self.ruleCollector = ruleCollector
  }

  public func generateContent() -> String {
    let sorted = ruleCollector.allLinters.sorted(by: { $0.typeName < $1.typeName })

    var result = """
      //===----------------------------------------------------------------------===//
      //
      // This source file is part of the Swift.org open source project
      //
      // Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
      // Licensed under Apache License v2.0 with Runtime Library Exception
      //
      // See https://swift.org/LICENSE.txt for license information
      // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
      //
      //===----------------------------------------------------------------------===//

      // This file is automatically generated with generate-swiftiomatic. Do not edit!

      @_spi(Internal) public enum RuleRegistry {
        public static let rules: [String: RuleHandling] = [

      """
    for rule in sorted {
      // Format rules default to .fix (auto-format); lint-only rules default to .warning.
      // Opt-in rules default to .off regardless of type.
      let defaultHandling: String
      if rule.isOptIn {
        defaultHandling = ".off"
      } else if rule.canFormat {
        defaultHandling = ".fix"
      } else {
        defaultHandling = ".warning"
      }
      result += "    \"\(rule.typeName)\": \(defaultHandling),\n"
    }
    result += "  ]\n\n"

    // Generate groupRules: [ConfigGroup: [(option, rule)]]
    var groupedRules: [ConfigGroup: [(option: String, rule: String)]] = [:]
    for rule in sorted {
      guard let group = rule.group else { continue }
      let option = Self.optionName(for: rule.typeName, stripping: group.rulePrefix)
      groupedRules[group, default: []].append((option, rule.typeName))
    }

    result += "  public static let groupRules: [ConfigGroup: [(option: String, rule: String)]] = [\n"
    for group in ConfigGroup.allCases {
      guard let rules = groupedRules[group], !rules.isEmpty else { continue }
      result += "    .\(group): [\n"
      for (option, rule) in rules {
        result += "      (\"\(option)\", \"\(rule)\"),\n"
      }
      result += "    ],\n"
    }
    result += "  ]\n"

    // Generate groupManagedRules: Set<String>
    result += "\n  public static let groupManagedRules: Set<String> = {\n"
    result += "    var names = Set<String>()\n"
    result += "    for (_, mappings) in groupRules {\n"
    result += "      for (_, rule) in mappings { names.insert(rule) }\n"
    result += "    }\n"
    result += "    return names\n"
    result += "  }()\n"

    result += "}\n"
    return result
  }

  /// Derives a short option name by stripping the group prefix and lowercasing the first char.
  private static func optionName(for typeName: String, stripping prefix: String) -> String {
    var name = typeName
    if !prefix.isEmpty, name.hasPrefix(prefix) {
      name = String(name.dropFirst(prefix.count))
    }
    guard let first = name.first else { return name }
    return first.lowercased() + name.dropFirst()
  }
}
